### ISSUE TITLE
Code Coverage Doesn't Reflect Files Which Aren't Included

### ISSUE THREAD

**Issue by jagreene** [tableau/webdataconnector#102]
Seems like a know [issue](https://github.com/istanbuljs/nyc/issues/333) with the --all flag in, nyc our coverage provider. Currently the flag raises an error and stops all tests, but once their issue is fixed we should add it to the unit:coverage and unit:coveralls npm commands to have our PRs more accurately display our code coverage stats.

**Comment by jimmy-jia** [comment]
Should we also add that windows is not supported for the unit:coverage run?
