### ISSUE TITLE
Dimensions vs Measures

### ISSUE THREAD

**Issue by gilbert-n** [tableau/webdataconnector#122]
I noticed that if I don't specify columnRoles while loading schema, then all variables with float or  int data types are automatically classified as measures in Tableau. On the other hand, variables with string data types are classified as dimension in Tableau. 
However, when I change my connector to specify the columnRoles and assign dimensions to those variables with number data types while I assign measures to the variables with string data types nothing changes in tableau i.e it looks like the columnRole field is ignored by Tableau. 

Is this an intended behaviour? If not, how can one enforce the dimension and measures of variables?

**Comment by lbrendanl** [comment]
Hey @gilbert-n,

Are you seeing this for all columns or just for some with certain names?  For all data types?  What version of Desktop / the WDC API are you using? I just tested in a recent version and I was able to successfully overwrite the column role for an int field.

**Comment by gilbert-n** [comment]
Hi @lbrendanl 

I am on Tableau 10.0.2 and WDC 2.0.  I am seeing this behaviour for all columns. In my particular case, the data I am dealing with have types: float/ int and string. Whether I set it or not, the column role field seems to be ignored by Tableau and always defaults to: string column -> dimension while float or int column -> measures.

**Comment by gilbert-n** [comment]
@lbrendanl 

I found out what was wrong. I fixed it, and it's working now. Thank you
