### ISSUE TITLE
connectionData and connectionName lost during "Start Auth Phase"

### ISSUE THREAD

**Issue by Jaxolotl** [tableau/webdataconnector#130]
React sends a warning while opening the connector in "Auth Phase"

### Steps to repro
- Open the ../Examples/html/earthquakeMultitable.html connector
- Hit the **Get Earthquake Data!** button on the connector UI
- Now click on the simulator the **Start Auth Phase** button

### Results:
The connectionName and connectionData field are cleaned up and a warning is displayed on the console inspector

### Expected:
The connectionName and connectionData remain intact and no warning is displayed

## Previous state
![screenshot_1](https://cloud.githubusercontent.com/assets/3777496/20601267/889e2330-b236-11e6-836b-976eff9f5941.png)

## Error
![screenshot_2](https://cloud.githubusercontent.com/assets/3777496/20601273/8b5e377c-b236-11e6-8aaa-1ef9cbfa1c3c.png)

## Error description and stack from the console
[connectionName and connectionData REACT error.txt](https://github.com/tableau/webdataconnector/files/611498/connectionName.and.connectionData.REACT.error.txt)

**Comment by lbrendanl** [comment]
Fixed.

**Comment by Jaxolotl** [comment]
Verified! awesome Brendan, thanks!
