### ISSUE TITLE
WDC API reference is full of 404s

### ISSUE THREAD

**Issue by craigkovatch** [tableau/webdataconnector#132]
Looks like it has a bunch of hard links to api_ref.html which has since been renamed/relocated.

**Comment by lbrendanl** [comment]
Thanks @craigkovatchl for reporting this.  We started the process of removing a separate docs branch yesterday (in favor of keeping the docs in master).  Looks like we missed these hardcode links.  @jdomingu can you take a look at this?

**Comment by jdomingu** [comment]
Did a grep and ran everything that I could find--let me know if there's anything I missed!
