### ISSUE TITLE
Simulator and AuthType Basic

### ISSUE THREAD

**Issue by SevereOverfl0w** [tableau/webdataconnector#142]
In my tests, I don't seem to be prompted to enter a username/password for a connector with this custom init:

```
    myConnector.init = function(initCallback) {
        tableau.authType = tableau.authTypeEnum.basic;
        initCallback()
    }
```

Am I doing something wrong? Or is this not currently supported by the simulator?

**Comment by lbrendanl** [comment]
Hey @SevereOverfl0w, this flow is not supported in the simulator. 

To be clear though, the basic auth dialog only pops up in re-authentication scenarios within Tableau - an example being when you open a saved workbook from a new instance of Desktop.  You will still need to use an html UI for your initial connection experience.

**Comment by SevereOverfl0w** [comment]
I see, the docs I read (https://tableau.github.io/webdataconnector/docs/wdc_authentication) really didn't make this clear. It implied that if the AuthType was set, the HTTP Basic Authentication prompt should open up automatically.

Did I miss some information on how to do this or do the docs need improving here to detail what is involved with the basic auth strategy?

Your instruction helped though, my WDC is now working.

**Comment by jdomingu** [comment]
Hi @SevereOverfl0w that's totally a doc issue :) Thanks for catching that. I'm assigning this to myself and I'll see what I can do to clarify.

**Comment by srini2833** [comment]
JDomingu, can you please be explicit on the docs if you are editing to state that Tableau desktop only supports Forms authentication and not Basic auth.

**Comment by jdomingu** [comment]
Sounds good! Thanks. I have some time set aside in the next couple of weeks to go through these doc issues. Appreciate the feedback!

**Comment by Shantam2** [comment]
@jdomingu Were the docs updated ? I see that adding basic auth still doesn't show the popup (in simulator or tableau browser)
