### ISSUE TITLE
Connector working in Simulator, but not in Tableau Desktop Client

### ISSUE THREAD

**Issue by joelperry93** [tableau/webdataconnector#144]
So I've got my connector working, and in the simulator it runs fine and I get data coming up in the table. When I run the connector via the desktop client, I get this error:

Either invalid data are present or required fields are empty for class TableInfo. Required fields and respective data types are: { (Name : 'id', Type : QString, IsRequired : true), (Name : 'columns', Type : QVariantList, IsRequired : true), (Name : 'alias', Type : QString, IsRequired : false), (Name : 'description', Type : QString, IsRequired : false), (Name : 'incrementColumnId', Type : QString, IsRequired : false) }

None of the columns are empty in the simulator. Are there any things I should check specifically or is there a way I can further debug this error message?

**Comment by joelperry93** [comment]
I think this might have been due to storing a very large object in tableau.connectionData. Perhaps Chrome supports larger object property sizes than the Tableau Desktop client browser.

**Comment by lsgs** [comment]
I had this trouble too - even with a small object in tableau.connectionData. Debugging showed that after assigning an object with connection properties to tableau.connectionData, it would only contain "[object Object]" as a string, not the object. As a result, my getSchema function was not getting the field information, and the columns property of the table was empty, hence the error message complaining about required things being missing.

I found a workaround by setting tableau.connectionData to be a json stringified string of the connection properties object, then parsing it back into an object for use in getSchema and getData.

```
            var connectionData = {
                exportFormat: exportFormat,
                token: $("input#token").val(),
                url: $("input#url").val()
            };
            tableau.connectionData = JSON.stringify(connectionData);
```
... then ...
```
    myConnector.getSchema = function(schemaCallback) {
        var connectionData = JSON.parse(tableau.connectionData);
        $.ajax({
            url: connectionData.url,
            // etc...
```

**Comment by YazidKrypto** [comment]
I have the same issue

**Comment by MinMiguelM** [comment]
I would like to re open this issue, I am having the same error.

When getSchema is called and I get connectionData, it's empty, therefore the getSchema throws an error because it cannot be parsed to JSON.

This error occurs intermittently and I haven't could figure it out if it is a Tableau's error or WDC's error.

I am testing on tableau public 2020.3, on version 2019.2 that error never happened me.

Thanks in advance
