### ISSUE TITLE
Add pagination to simulator results

### ISSUE THREAD

**Issue by lbrendanl** [tableau/webdataconnector#148]
When a large number of rows are returned during the getData call, the simulator will display all the data, which can cause the page to freeze.  The simulator should not display all of of the data, but show it in pages with some page controls.

**Comment by smohtadi** [comment]
Hi! Is this issue still open? I would like to work on it.

**Comment by theoutlander** [comment]
Since WDC-3 will be coming out this year, I'm closing this item as we won't be working on it.
