### ISSUE TITLE
XML Parser Sample download from URL doesn't return correct table

### ISSUE THREAD

**Issue by yanjing2** [tableau/webdataconnector#15]
when i use WEB connector--xmlConnector.html to connet my data,then there are 2 output.
1.when input URL,and the output got wrong

2,when past a XML file in xmlConnector,and get correct.
i don't know why Input URL will go wrong?

**Comment by lbrendanl** [comment]
Hey @yanjing2, could you specify with an example?  Are you able to share the URL of the XML you are looking to collect? How exactly is the output wrong? 

I tried one and it looked like the when I used the URL input method, one of the returned columns was missing.  Is that the same issue you are seeing?

**Comment by yanjing2** [comment]
yes,my issue is the false table structure,the data of  rows and columns look disordered and some data was missing.
but when i open the URL in a browser and then paste the URL from browser to the web connector--XML connector.html,it returned a correct data,i can not understand why,it seems the WEB connector is unstable.

**Comment by lbrendanl** [comment]
I've spent a bit of time investigating this. For the sample I am was using, the query parsing service the sample uses (Yahoo) is returning the wrong results interestingly enough.  It seems to work for certain XML docs but has problems with another.

**Comment by lbrendanl** [comment]
Close as we are no loner actively developing the V1 samples - they are still available within our github releases.
