### ISSUE TITLE
WDCs get hung up in Tableau

### ISSUE THREAD

**Issue by csg5046** [tableau/webdataconnector#150]
I am using Tableau v 9.3.1 and attempting to simply run one of the example WDC's as well as the one I built through the Tableau tutorial. I followed the older tutorial due to my older version of Tableau, and I was able to successfully run the WDCs in the older version of the simulator. I am using the 1.1.1 library, as instructed in the Tableau tutorial for my version of the software.

Whenever I attempt to run the WDC in Tableau, it gets hung up in the 'Executing Query' stage, and therefore I cannot successfully pull data into Tableau with any of the example WDCs. There are no errors in the code when running them in the simulator, but I did have to turn off 'Compatibility Mode' for them to run properly.

**Comment by judexavier** [comment]
Hello there, were you able to solve this problem. I seem to having the same with my WDC. It seems to work fine in the simulator but fails when trying in desktop. The error i see in the debugger is "**Network error occurred: Error 6 (SSL handshake failed)**"

**Comment by judexavier** [comment]
I got mine resolved. It was an issue from the client side with respect to domain configuration.  The below link helped to identify the exact issue when Tableau Desktop hung up 
[](https://tableau.github.io/webdataconnector/docs/wdc_debugging#debugging-tableau)

Try to open desktop in debug mode and identify what is causing the issue.

**Comment by SkyCorpFr** [comment]
Hello everybody,
I have the same problem (or at least a similar problem) on Tableau Public 10.2.1.
I can follow successfully the tutorial (http://tableau.github.io/webdataconnector/docs/wdc_tutorial) with the simulator.
On Tableau Public, I use the URL http://localhost:8888/earthquakeWDC.html (the file is located in the webdataconnector directory) for the Web Data Connector, then I clic on "Get Earthquake Data!". Then Tableau Public asks me to "Update Now" ou "Automatically Update".
No matter where I clic, Tableau Public stays stuck. And I don't see anything special with the debugger.

Any idea?

**Comment by ewreck** [comment]
Hey SkyCorpFr

I was having the exact same problem.

Turns out, the URL for the json data is https:// while the tutorial has the URL as http://

I made that single letter update after banging my head against a wall for 3 days and it is now working for me.  Hope that helps.

**Comment by lbrendanl** [comment]
Thanks @ewreck, appreciate the comment and our huge apologies for the trouble you went through! I've fixed this in the tutorial.

**Comment by JyothirmaiT** [comment]
Hello everyone, 
I'm facing a similar problem with the WDC I built, it works pretty well with the simulator but when I connect through tableau desktop (ver 2018.1)  it connects successfully but when I hit update now it keeps on loading but data never shows up (it's just 2 rows data). I tried using the debugger but even debugger does not load if I hit F8, everything hangs and then I had to close.
If anyone has any idea why this is happening, please help!

**Comment by SaidaRezyapovaG** [comment]
@JyothirmaiT Hello!
Have you resolved your problem? 
I have exactly the same issue and I would be very thankful if you can help me with it..

BR,
Saida

**Comment by JyothirmaiT** [comment]
Hi Saida,
I got this issue because I had a CORS issue. The server on which WDC is hosting is not CORS enabled. Please install corsproxy-https on your server, it works!

**Comment by SaidaRezyapovaG** [comment]
@JyothirmaiT Hi! Thank you very much!
