### ISSUE TITLE
Share Auth Cookie between Interactive phase and gather data phase browser sessions

### ISSUE THREAD

**Issue by BakedSweetPotato** [tableau/webdataconnector#152]
Hi,

I'm making a WDC that requires the user to be logged in to the website before the page loads. The authentication check is done at the backend. If the current user is authenticated, the WDC page will display. Otherwise, the user will redirect to the login page where the authentication cookie is set.

The problem is during the data gathering phase, Tableau will launch the WDC in a new headless browser session which does not include the authentication cookie set in the interactive phase. As result, the Tableau desktop client will redirect to the login page and the actual WDC page never loads. So, is there a way to share the auth cookie between each browser session?
 
Here is the log that I got from `tabprotosrv.txt`

```json
{
  "ts": "2017-01-28T14:15:23.007",
  "pid": 8141,
  "tid": "c3ad3d",
  "sev": "info",
  "req": "-",
  "sess": "-",
  "site": "{44F6B3A5-9A81-45B4-B9BA-56DB45E136EF}",
  "user": "-",
  "k": "web-data-connector",
  "v": "Web view loading finished. Loading was successful. Loaded url is 'https://www.test.com/user/sign-in/?ep=%2Fintegrations%2Ftableau%2Fwdc%2F61152%2F'",
  "ctx": {
    "client-type": "desktop",
    "procid": "188",
    "tid": "11971428",
    "version": "10000.16.1223.0117"
  }
}
```

[Here](https://community.tableau.com/thread/221604) is a very similar question from Tableau Community.

**Comment by hmrasi** [comment]
Hi guoyo,
We are facing the same issue while using the WDC in tableau.
The cookie is not transferring from Interaction Phase to Gather Data Phase.

Can we have any solution for this?
Can you please explain how you resolved the issue in your scenerio?

Thanks,
hmrasi
