### ISSUE TITLE
CORS issue with WDC basic tutorial 

### ISSUE THREAD

**Issue by judexavier** [tableau/webdataconnector#159]
Hello All ! 
I downloaded WDC SDK today and was going through the basic tutorial for getting earthquakeUSGS data. while do so during Fetch Data phase, the API call fails with CORS error. This is happening for the existing app in "http://tableau.github.io/webdataconnector/Simulator/". 

Can anyone let me know if i am doing anything wrong from my end?

Thanks,
Jude

**Comment by laurier-l** [comment]
Hi Jude,

I just came to the same conclusion.  Perhaps this is a recent change on the USGS server that restricts this.

If you go to the page at [https://tableau.github.io/webdataconnector/docs/wdc_cors](url) and follow the instructions in step 2 for your javascript code, then it should work.

I hope they update the tutorial instructions and related code.  This would have saved me a couple of days of messing around.

**Comment by laurier-l** [comment]
...and my link didn't work.
Let's try this again:
https://tableau.github.io/webdataconnector/docs/wdc_cors

**Comment by lbrendanl** [comment]
Thank you for reporting this! Looks like this is caused by a recent change to the API we are hitting in that sample.   We will investigate and get the samples fixed up shortly.

**Comment by judexavier** [comment]
Thanks Brendan and laurier !  
I am very new to WDC and scripting and was wondering if it was an issue from my end.

**Comment by judexavier** [comment]
Sorry Closed it by mistake!!!

**Comment by lbrendanl** [comment]
Hey @judexavier, @laurier-l,

This should be fixed now, please verify it's working for you then close the issue if so.  Let me know if it's not working for you.  

Thanks!

**Comment by judexavier** [comment]
Thanks Brendan, 
I am able to run the WDC examples now from my local simulator.
