### ISSUE TITLE
tableau.init not being called

### ISSUE THREAD

**Issue by arb** [tableau/webdataconnector#165]
I'm trying to write my first WDC and I am having trouble getting it to work with the simulator. I started my app as a react app with a basic form to pass information to a database. Upon executing `tableau.submit()` I get the following errors:

![image](https://cloud.githubusercontent.com/assets/1591483/23957893/e1b8a3e0-0976-11e7-8b36-18848a8d42c1.png)

When I step through `SimulatorDispatcher.prototype._sendMessage` I see that `typeof this.globalObj.webkit != 'undefined'` is `false` and `!this._sourceWindow` is also `false` and the throw happens there.

When I start up the simulator and point it to "http://localhost:3000" and start interactive mode, my react app loads up fine. When I click my form submit button, that's when my error happens. 

Below find relevant JS code

```js
class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {};
    this.conn = window.tableau.makeConnector();

    this.conn.getSchema = function (done) {
      alert('getSchema');
      window.tableau.log('done');
      done();
    };

    this.conn.getData = function (table, done) {
      alert('getData')
      window.tableau.log('getData');
      done();
    };

    window.tableau.registerConnector(this.conn);
  }
  handleSubmit = (event) => {
    event.preventDefault();
    setTimeout(() => {
      window.tableau.connectionName = 'Foo';
      window.tableau.submit();
    }, 3000);
  };
  render() {
    return (
      <div>
        <form onSubmit={this.handleSubmit}>
           ... // form inputs
          <input type="submit" value="Execute Query" />
        </form>
      </div>
    );
  }
}
```

Neither of the `alerts` pop during execution so those functions are not being called.

## Update 1

I was using a script loader to load the SDK before my app started as I'm not a huge fan of just slapping script tags in `<head>`. I made the change and just put the script tag in the head element and it started working. Not sure what difference that could have made?

**Comment by k504866430** [comment]
I faced the same issue. The problem lies in the sdk, specifically-

```js
SimulatorDispatcher.prototype._initMessageHandling = function() {
	  console.log("Initializing message handling");
	  this.globalObj.addEventListener('message', this._receiveMessage.bind(this), false);
	  this.globalObj.document.addEventListener("DOMContentLoaded", this._onDomContentLoaded.bind(this));
	}
```
If you are using the script loader, it's already too late to bind to 'DOMContentLoaded' event.

You need to dispatch the event artificially after the sdk is loaded. I did the following to make my connector work on Simulator-

```js
var DOMContentLoaded_event = window.document.createEvent("Event")
            DOMContentLoaded_event.initEvent("DOMContentLoaded", true, true)
            window.document.dispatchEvent(DOMContentLoaded_event)
```

This will work fine because SimulatorDispatcher passes messages between the popup window and parent window-
```js
SimulatorDispatcher.prototype._receiveMessage = function(evt) {
	  console.log("Received message!");

	  var wdc = this.globalObj._wdc;
	  if (!wdc) {
	    throw "No WDC registered. Did you forget to call tableau.registerConnector?";
	  }

	  ..........

	  switch(payloadObj.msgName) {
	    case "init":
	      this.globalObj.tableau.phase = msgData.phase;
	      this.globalObj._tableau.triggerInitialization();
	      break;
	   .......
	  }
	};
```

Now, here's the other problem, this is not working on tableau desktop because it appears the NativeDispatcher works differently. 
Someone from the SDK team should help figure out how to support async loading of sdk and connector registration, or help us understand how we can force Tableau desktop to fire 
```js
this.globalObj._tableau.triggerInitialization();
```

**Comment by arb** [comment]
Wow. Great investigation! Looks like way too many hacks though to really be viable at this point.

**Comment by ataft** [comment]
Has anyone figured this out? I'm using a script loader (requirejs).

I could load this script in the <head>, but can't define the connector getSchema and getData methods until a later time in the app. Maybe this is somewhat related to issue #25?

**Comment by contra** [comment]
@arb Not interested in fixing this in the connector simulator? It should check if the content is already loaded and call initialization, otherwise wait for the event to call it. It should be a 1 line fix.

**Comment by arb** [comment]
Go for it @contra. I haven't done anything with tableau for many months now 😄

**Comment by contra** [comment]
@arb Ah, just assumed you worked there if you're closing tickets. Can you reopen this and assign it to me?

**Comment by arb** [comment]
I can't assign it to you; I'm just another random GitHub person. But I did reopen it for you.

**Comment by contra** [comment]
@arb Thanks

**Comment by a-d-collins** [comment]
None of the samples listed in the docs (http://tableau.github.io/webdataconnector/docs/wdc_samples) work because of this issue. Is a fix expected in any future release?

**Comment by duongthienlee** [comment]
Any updates on this ? , I tried @contra  's solution, but it still doesn't work for me.
