### ISSUE TITLE
What kind of browser does Tableau Desktop use?

### ISSUE THREAD

**Issue by jakegarelick** [tableau/webdataconnector#171]
I vaguely remember running into some ES6 issues when trying to make my own web data connector.  Is the desktop browser based on some other browser? This could be helpful to know the limits of what kind of JavaScript I can write.

**Comment by lbrendanl** [comment]
The current browser is WebKit from QT version 5.4.  I don't remember off the top of my head if that was based on another browser....  Most (if not all) ES6 syntax is not supported, but usually polyfilling what you need works.

**Comment by jakegarelick** [comment]
Good to know thanks. Might be something useful to have in the tutorial/documentation (specifically the part about ES6 not being supported).

**Comment by lbrendanl** [comment]
There is an entry in the FAQ with a bit of detail, but you're totally right that it would be useful to have this information earlier on to save developers some trouble.  @jdomingu what do you think about mentioning this earlier in the docs?

**Comment by lbrendanl** [comment]
Added a note to the start of the tutorial.
