### ISSUE TITLE
Tableau Desktop Browser renders poorly on a Mac Retina screen

### ISSUE THREAD

**Issue by mineshpatel1** [tableau/webdataconnector#176]
Elements can appear blurry and unreadable, not simply just not anti-aliased. I understand the browser is a QT 5.4 WebKit browser, but it is difficult to debug this behaviour.

Is there any assistance you could provide regarding testing our pages in the native browser?

**Comment by tagyoureit** [comment]
10.4 will support High DPI displays.  Hopefully this will fix the issue. [10.4 Coming Soon](https://www.tableau.com/coming-soon/10.4#tab-enterprise-2)

**Comment by mineshpatel1** [comment]
After some debugging, it appears this is to do with CSS animations used in the HTML which aren't supported by the QT browser. Removing those animations improves the quality greatly. This bug doesn't occur on the Windows version of the WDC, only on Mac. I think the Retina screen was a red herring.

**Comment by lbrendanl** [comment]
Thanks for the follow up @mineshpatel1, and apologies for the difficult in working with QT WebKit.

**Comment by ataft** [comment]
This upgrade would be great to allow for using flexbox too
