### ISSUE TITLE
WDC slow processing of data - String type specific

### ISSUE THREAD

**Issue by larhill66** [tableau/webdataconnector#187]
I have a Client who is having issues with String type data when pulling form source. The WDC takes a very long time to process and pegs the CPU at 100%. 

**Excerpt**: "We are loading daily time series data, with around 1,000 values per day. We have a String type column that contains a unique value per day (so about 1,000 unique values). And there is around 30 days of this data. So around 30k rows of data total.
 
Tableau Desktop takes around 8 minutes to process this data. This is after we have called appendRows from the WDC SDK so after our code is done with it. While it is loading, we can see that the tabprotosrv.exe process is consuming 100% of one cpu core for the full duration of the processing. So this leads me to believe all of this processing is happening within Tableau Desktop itself.
 
With this same 30k rows of data, if we exclude this String type column but keep the rest of the data the same (still have 1,000 values per day for 30 days), the data will process in around 5 seconds.
 
So somehow whatever Tableau is doing on the String values (indexing? analyzing? etc) is taking a huge amount of time. If this String type column only contains a small set of values (say 50 for example) then it loads in under 10 seconds as well. So it only happens when there is a large amount of unique values per day.
 
Have tried this on Tableau Desktop 10.1 and 10.2. If I test this same data as a CSV import Tableau processes it relatively fast so it seems like a problem specific to WDC.
 
Is this expected behaviour? I can't imagine that loading 30k rows of data taking 8 minutes is normal."

**Comment by lbrendanl** [comment]
Thanks for the amount of detail here, very helpful.  

A few followup questions:
1) How wide is the data? 30k rows but how many columns per row? 
2) When they say "If this String type column only contains a small set of values (say 50 for example)", do they mean if the column only contains a small set of unique value, but still 30k rows?
3) For the testing with CSV, did they import the data as an extract or just connect to it live (the default).  

One thing you could try immediately on your end is sending the data back in pages, i.e. call appendRows with 100 rows, 300 times.  

It does sound like there is some sort of bug in play here, but the above will help us narrow down where that is.

**Comment by jordandev** [comment]
Here is a sample of a selection of the data:

> Curve Name,Curve Type,Effective Date,Granularity,Number of Records,Curve Value
> TGP-Z4 Sta-219 Price,Price,2017-01-01,Daily,1,3.222
> TGP-Z4 Sta-313 Price,Price,2017-01-01,Daily,1,3.1398
> TGP-Z5 200L Price,Price,2017-01-01,Daily,1,4.65
> TGP-Z6 200L Price,Price,2017-01-01,Daily,1,6.1186
> Transco Leidy Line receipts New Jersey Price,Price,2017-01-01,Daily,1,3.1461
> Transco Zn3 Louisiana Price,Price,2017-01-01,Daily,1,3.5214
> Transco Zn4 Alabama Price,Price,2017-01-01,Daily,1,3.0713
> Transco Zn6 NY New York Price,Price,2017-01-01,Daily,1,3.2977
> Transco-30 Texas Price,Price,2017-01-01,Daily,1,3.477

So the "Curve Name" column there is the one that will have around 1,000 unique values across the 30k rows. If that column is removed (and the rest of the data is the same) it will import into Tableau in around 5 seconds. Otherwise with it included, 8 minutes.

We can try paging the appendRows call and see what that does.

**Comment by lbrendanl** [comment]
Closing for lack of response, please re-open if needed.
