### ISSUE TITLE
WDC simulator not accessible ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by boconne27** [tableau/webdataconnector#190]
I am having issues reaching the WDC Simulator on my MAC.  I am using chrome and have tried clearing the history, changing proxy/firewall settings, restarting web browser, etc but I am still having issues connecting to the WDC Simulator for Tableau.  It always says ERR_CONNECTION_REFUSED in chrome.  While tyring this website below in Safari, it says Safari can't find this server.  Here is the address I am trying to reach:
http://localhost:8888/Simulator/index.html

I have installed the necessary software per the instructions here:
http://tableau.github.io/webdataconnector/docs/

**Comment by tagyoureit** [comment]
You may have another application that is using that port.  

```
By default, the test web server runs on port 8888. To change the port number, edit the http-server script in the package.json file. For example, you might enter the following to change the port to 8000:

"http-server": "node node_modules/http-server/bin/http-server -p 8000"
```

From [docs](http://tableau.github.io/webdataconnector/docs/wdc_debugging.html)

**Comment by lbrendanl** [comment]
@boconne27 did that suggestion solve your problem?  I agree with @tagyoureit's assessment.   I am closing this issue for lack of a response, please reopen if you are still experiencing problems.
