### ISSUE TITLE
[Question]: Tableau error after submit - user has not yet visited the url

### ISSUE THREAD

**Issue by MarcusKohnert** [tableau/webdataconnector#193]
I get the following error after trying to submit a webdataconnector to Tableau.

![tableauerror](https://user-images.githubusercontent.com/1331392/29076234-29f65ee4-7c55-11e7-9d10-e71e872ae6cb.PNG)

Background:
* Angular 4 TypeScript application
* Tableau 10.3.2
* tableauwdc-2.0.latest.js

It works in the simulator.

Debugging Tableau doesn't work unfortunately because the error occurs before the debugger starts.

Any advice on how we could investigate the problem any further?
Thanks in advance!

**Comment by MarcusKohnert** [comment]
My colleague provided a sample repo [here](https://github.com/Olddude/tableau-error) trying to reproduce the issue. Unfortunately it shows a different behaviour. Simulator works. But in the Tableau browser there seems to occur a javascript error. The App is not loaded. Again very difficult to find out what's going on...

**Comment by Olddude** [comment]
Here ist the sample repository where this error can be reproduced.
https://github.com/Olddude/tableau-error.

Inside the WDC Simulator 2.0 the error does not occure. Inside Tableau 10.1 however, the application behaves like explained above.

Please follow the instructions in https://github.com/Olddude/tableau-error/blob/master/README.md
and if you have any suggestions I would be very happy if you can send me or Marcus a message.

**Comment by Olddude** [comment]
Hello @lbrendanl,

thanks for replying, we appreciate it very much! Now we do understand the issue background and why it behaves the way it does. Unfortunately in our real life environment the workaround would double our traffic. The user first has to route all the way from the root url -> http://localhost:4200/ to the actual target data url where the schema and data information lives -> http://localhost:4200/{resource}/{id}/tableau. Then the user has to copy the current data url, paste it inside Tableau WDC and repeat his request.

Is there maybe a way to delay the web data connector initialization inside the interactive phase or is there a way to reinitialize it once we got to http://localhost:4200/{resource}/{id}/tableau ? I've some comments about re-throwing the DOMContentLoaded event manually but without any success yet...

Thank your very much for your time!

**Comment by lbrendanl** [comment]
I looked into it on my end to see what the precise trigger is for the message.  We only show the error if the submit function is called before the page with the WDC is fully loaded. 

If your case, it appears that the WDC is initialized on the http://localhost:4200, but submit is called when the URL is pointing to  http://localhost:4200/{resource}/{id}/tableau.  And it appears that  http://localhost:4200/{resource}/{id}/tableau page has not been fully loaded in the browser.

So I think you could definitely get it to work without the user having the copy paste any additional URL, but just ensure the schema/data page is fully loaded by the browser before calling submit.  

Hmm another possibility that comes to mind is that the WDC is initialized from a different page than it is submitted from, is that true? 

@Jaxolotl you ever come across anything like this while building connectors? 

@Olddude, Jax is our engineering lead on an internal team here that builds our own connectors, so he's got a ton of expertise and might see something I'm missing :)

**Comment by jozsi** [comment]
I'm also experiencing this issue. I've previously written a simple, one-page connector with jQuery, it worked great. Now I have a React app with routing, the user enters `/`, goes through a couple of routes, then comes back to `/` and submits from there. Interestingly, the error message says the user hasn't visited the root URL that he manually input to get started. So it's not even the case of different entrance URL vs. submit URL.

**Comment by ghaskins** [comment]
This still seems to be an issue with Tableau Desktop 2022.4 and SDK 2.4.  It's not clear if there is a solution?
