### ISSUE TITLE
Error when testing in simulator

### ISSUE THREAD

**Issue by aBOBination** [tableau/webdataconnector#203]
Hi I am trying to run the example and getting hung up when testing in the simulator:

This site can’t be reached

file’s server DNS address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

This is the error I receive when I "Start Interactive Phase"

Here is what I have in my .js file
`(function () {
    var myConnector = tableau.makeConnector();

    myConnector.getSchema = function (schemaCallback) {
    tableau.log("Hello WDC!");
};

    myConnector.getData = function (table, doneCallback) {

    };

    tableau.registerConnector(myConnector);
})();
$(document).ready(function () {
    $("#submitButton").click(function () {
        tableau.connectionName = "USGS Earthquake Feed";
        tableau.submit();
    });
});`

**Comment by rajabandla** [comment]
I have similar problem. Did you resolve your issue. Appreciate it.

**Comment by ani0989** [comment]
Have you tested the connection after doing npm start ?

**Comment by rajabandla** [comment]
You mean using existing connections then yes and also returns data but not
my custom page which deployed in Github. Any idea?

**Comment by ani0989** [comment]
Can you put your custom code in here so we can assess the situation better ?
