### ISSUE TITLE
The user has not yet visited the url on this machine

### ISSUE THREAD

**Issue by tmixa82** [tableau/webdataconnector#204]
We are attempting to host our own web data connectors on our in-house Tableau servers.  I'm at a loss as to why I keep getting this error when I try using this connector.

The needed files have been imported via tabadmin and the urls have been whitelisted.  The main js file calls out to another rest api and I have added that url to the secondary whitelist for the connector.  There is no submit button as the connector does not require any user interaction.

Any clue as to what I could be missing?

-Tracy

**Comment by lbrendanl** [comment]
@tmixa82 can you clarify where and how you are seeing this error? When connecting via Tableau Desktop or is this showing up in the Server logs?

In the meantime, there is a bit of conversation [here ](https://github.com/tableau/webdataconnector/issues/193) around this error that might be helpful.
