### ISSUE TITLE
File Not Found: webdataconnector/../StockQuoteConnector

### ISSUE THREAD

**Issue by thleo** [tableau/webdataconnector#208]
When attempting the tutorial here: https://public.tableau.com/en-us/s/resources
And visiting the examples page here: https://tableau.github.io/webdataconnector/docs/wdc_samples

When trying to load the web data connector for stocks, 404 file not found issue is returned.

URL: https://tableau.github.io/webdataconnector/Examples/html/StockQuoteConnector_promises.html

![image](https://user-images.githubusercontent.com/23345283/30623169-fb58a8c6-9d83-11e7-8448-229192ddb781.png)

**Comment by lbrendanl** [comment]
Thanks @thleo.  

That sample was removed awhile ago because Yahoo took down the APIs the sample used.  I've removed it from the docs and will get it on the backlog to re-record a tutorial video.
