### ISSUE TITLE
Simulator Unresponsive after Interactive Phase

### ISSUE THREAD

**Issue by jolllof** [tableau/webdataconnector#211]
Hello, 

So I am working through the simulator, once i click the "Start Interactive Phase" and it opens a new window for the Connector URL i selected, the "Get Data" button is then not responsive, any suggestions or ideas. I have tried in both Chrome and Firefox. Thanks!

**Comment by ani0989** [comment]
As soon as you open the index.html page, could you open the inspect option in chrome and paste the console logs that appear once you click "Get data" option ? This will help debug the issue.

**Comment by lbrendanl** [comment]
@jolllof, as @ani0989 suggested, grabbing any errors you can find in the logs will help diagnose the issue.

You can right click anywhere in the popup window of the interactive phase, click 'Inspect' then navigate to the 'Console' tab in order to find the logs.

**Comment by dandata123** [comment]
Hi - I am having this same issue. Here's my error message:

Warning: Failed Context Types: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types

Thanks!

**Comment by chenteng2016** [comment]
Please help reopen if there is still an issue. Thanks for contributing to webdataconnector!
