### ISSUE TITLE
Update TableInfo documentation to reflect prohibited characters

### ISSUE THREAD

**Issue by RandallKent** [tableau/webdataconnector#215]
When working through the [Tutorial](http://tableau.github.io/webdataconnector/docs/wdc_tutorial), I learned that [`TableInfo.id`](http://tableau.github.io/webdataconnector/docs/api_ref.html#webdataconnectorapi.tableinfo-1.id-1) cannot contain a `-` when I encountered the error:

```
Id is invalid
```
Screenshot: ![screenshot 2017-10-23 23 10 20](https://user-images.githubusercontent.com/51821/31923209-627e31aa-b847-11e7-8d11-a3c64fa567a1.png)

I'll submit a PR to add a note to the WebDataConnectorAPI reference about the `-` character. Not sure if there is an exhaustive list of prohibited characters or if you think a comment should be added to the tutorial as well.

**Comment by lbrendanl** [comment]
Thanks @RandallKent, I accepted your PR so closing this issue.  We have some documentation incoming soon from @d45 that talks about this limitation and the other illegal characters.
