### ISSUE TITLE
Backwards Compatibility with older Tableau Versions

### ISSUE THREAD

**Issue by samdavey** [tableau/webdataconnector#22]
Receive the following error when accessing from 9.2:
"The version of Tableau that you are using cannot use the web data connector that you are trying to access. The connector requires at least version '1.1.1' of the web data connector API."

Is there a way to maintain backwards compatibility with the older API?

**Comment by benlower** [comment]
@samdavey can you please share a bit more about how you're hitting this issue? also which connector is this for (one in particular or all of them)?

**Comment by lbrendanl** [comment]
@samdavey This should be fixed now.  I have reverted the hosted samples on the gh-pages so they will continue to work as expected in Desktop.  Please confirm and I will close this.

**Comment by samdavey** [comment]
Hi team, the issue seems to be resolved. Thanks!
Note that the above error messages were still returned the next time that I attempted to use the connector (Google Sheets Connector), but after ignoring the error and using the Sign In link, I was able to successfully connect. Repeating it a second time did not return an error and again successfully connected. 
Thanks and regards,
Sam
