### ISSUE TITLE
WDC not prompting for username and password in basic auth type

### ISSUE THREAD

**Issue by h-patel** [tableau/webdataconnector#222]
Already set the auth type to basic as suggested in the documentation but its not prompting the username and password.

// Init function for connector, called during every phase
    myConnector.init = function(initCallback) {
      debugger
      tableau.authType = tableau.authTypeEnum.basic;
      initCallback();
    }
Missing anything?

Thank you
Hrushikesh Patel

**Comment by kacper-sokolowski** [comment]
+1. I am getting the same thing.

**Comment by Shantam2** [comment]
+1 I'm seeing the same issue as well.

No pop-up. I even tried with this

```
 myConnector.init = function(initCallback) {
      tableau.authType = tableau.authTypeEnum.basic;
	  tableau.username = "my_username_here";
	  tableau.password = "my_pass_here";
      initCallback();
  }
```

**Comment by marcelodive** [comment]
Same issue here. Is there some workaround?

**Comment by PrabhuSelvaraj300** [comment]
Can you share your HTML file? how it is defined?

**Comment by vinczemarton** [comment]
I have the exact same issue here, I shared my details on this ticket: https://github.com/tableau/webdataconnector/issues/160#issuecomment-858721905

There is no basic authentication example anywhere (or I cannot find it).

**Comment by KeshiaRose** [comment]
Hi all, I just made a sample to show how this works. The sample only uses an API key as the password but the process is the same for username & password. The idea is that you would ask the user for their username and password in your own text boxes within the interactive phase (when the dialog window is open). You then store this information in tableau.username and tableau.password. While the workbook is open, the password will remain but once it is closed it is no longer saved. The next time the workbook is opened and the user wants to access/refresh the data it will prompt for username and password. The prompt **only** occurs after the connection has already been configured and the password has been lost (from closing Tableau). (Note: the password can be embedded if published to Tableau Server/Online for future automated refreshes) Here is a [screen capture](https://user-images.githubusercontent.com/19785852/121627505-4fbb9f80-ca2c-11eb-94e0-fe0659a59fe2.mp4) of the sample and you can find the code [here](https://glitch.com/edit/#!/ticketmaster-events-wdc?path=README.md).

-Keshia

_(Reposted response from #160 for visibility)_
