### ISSUE TITLE
Tableau Server API Request (Error Code 401001)

### ISSUE THREAD

**Issue by iamsaanvi** [tableau/webdataconnector#223]
Hi All,
 
I am getting Error: Publish to [Tableau Server](https://mindmajix.com/tableau-advanced-training) (21): TableauServer.Login: Tool #4: Tableau Server API Request (Sign-in) Error Code 401001: Signin Error -- Error signing in to Tableau Server.
 
I am using connect with server and site.
I am able to use same credential to login to my tableau website without issue.
 
Any help?

Thanks in Advance
Saanvi S

**Comment by craigbloodworth** [comment]
This Github repo is for web data connector issues, not REST API.
