### ISSUE TITLE
Geometry Data Type doesn't work in 10.4

### ISSUE THREAD

**Issue by craigbloodworth** [tableau/webdataconnector#226]
Using Tableau 10.4.0 or 10.4.1 and the WDC https://www.tableaumapping.bi/wdc the geometry column returns null values for both polygon and polyline data types. In 10.5 beta it works just fine.

The WDC uses the 2.3.0 version of the WDC JS file.

**Comment by lbrendanl** [comment]
Hey @craigbloodworth, are you testing this on a mac? Unfortunately 10.4.0 and 10.4.1 have a bug that was introduced late in the dev cycle that we missed on mac.  This will be fixed in 10.4.2 and 10.5.  Apologies for the frustration there, this was something we missed on.

**Comment by craigbloodworth** [comment]
Hi @lbrendanl, yes this was on a Mac.

Is there any place to publish known issues like this against the release version?

**Comment by lbrendanl** [comment]
There is a general known issues page on the main corp website, but perhaps a better place would be here: [https://tableau.github.io/webdataconnector/news/](https://tableau.github.io/webdataconnector/news/)

That page serves as our release notes page currently (though I want to revamp it to look more like this [https://tableau.github.io/extensions-api/docs/trex_release-notes.html](https://tableau.github.io/extensions-api/docs/trex_release-notes.html)).  

Question for you, where is a place you would've looked for this kind of thing so we could've saved you some time?
