### ISSUE TITLE
Does WDC supports ES2015?

### ISSUE THREAD

**Issue by welkinlan** [tableau/webdataconnector#227]
Are promise / arrow functions supported for current version of WDC?

Thanks!

**Comment by lbrendanl** [comment]
Hey @welkinlan,

ES2015 is not currently supported.  The reason is that, when in Tableau, the WDC is run inside a browser that is currently a bit old (QTWebKit 5.4).  We have plans to upgrade this in the future to a browser that does support more modern JavaScript features.

**Comment by welkinlan** [comment]
@lbrendanl Thanks!
