### ISSUE TITLE
How to show errors/warnings for WDC in Tableau Desktop

### ISSUE THREAD

**Issue by welkinlan** [tableau/webdataconnector#228]
Hello,

In the Tableau Desktop, is there a good way to inform users warnings / errors during say Gather Data phase? A good example is when the user query was malformed, or the user's auth token expired.

Thanks,
Tian

**Comment by lbrendanl** [comment]
Hey @welkinlan,

For general areas, we recommend using abortWithError, a method on the tableau object.
https://tableau.github.io/webdataconnector/docs/api_ref.html#webdataconnectorapi.tableau.abortwitherror

**Comment by welkinlan** [comment]
@lbrendanl Thanks that helped!
