### ISSUE TITLE
Data refresh failed - Cognetik Web Data Connector

### ISSUE THREAD

**Issue by nelsonlai82** [tableau/webdataconnector#229]
Hi all,
I am using Cognetik Web Data Connector to extract data from Adobe Analytics.
I am able to extract and refresh data in my tableau desktop.

The issue is - after i published the workbook into tableau server, the job of data extract is failed.
Error message is
Error: com.tableausoftware.nativeapi.dll.DataSourceException: WebDataRequestor::InitAPIObj Unable to load URL: http://tableau.cognetik.com:80/connector.html

I have followed all the steps as in https://cognetik.zendesk.com/hc/en-us/articles/115001318331--Refreshing-Data-Extracts-on-Tableau-Server-

But job still failed.
[Cognetik Issue.docx](https://github.com/tableau/webdataconnector/files/1562008/Cognetik.Issue.docx)

Any expert can help? Thanks!

**Comment by lbrendanl** [comment]
Hi @nelsonlai82,

You'll want to reach out to the team that built the connection in question.  This repository is focused on the developer APIs and tools for building web data connectors, we don't have any insight into the specific connector your mentioned.

For what it's worth, from just the error you mentioned, it sounds like the web page of the WDC (http://tableau.cognetik.com:80/connector.html) is being blocked somewhere on Server, perhaps by a firewall? 

Thanks,
Brendan

**Comment by nkalupahana** [comment]
@nelsonlai82 Was this ever resolved, and if so, how?

**Comment by crisfoit** [comment]
hey there,

Daexus (official tableau partner) released a free web data connector for Tableau @nkalupahana 
https://www.daexus.io/products/?utm_medium=gt&utm_source=social&utm_campaign=oa#online
it's free. secure, and easy to use - no sign up or download required - only runs on your computer, data doesn't get passed through external servers/
