### ISSUE TITLE
Error connecting to google sheet

### ISSUE THREAD

**Issue by Anuponk** [tableau/webdataconnector#23]
Hello,
i try to connect tableau to a google sheet using this procedure: http://onlinehelp.tableau.com/v9.2/pro/online/windows/fr-fr/help.html#examples_web_data_connector.html

But when Tableau tries to load the data i have the following error:

![capture](https://cloud.githubusercontent.com/assets/17879760/13813163/47727f3c-eb80-11e5-920a-814c7c4430ff.PNG)

Does somenoe knows what should i do?
thanks for your help,
Cédric

**Comment by lbrendanl** [comment]
Hey @Anuponk, what version of Tableau are you using? Also, which connector are you using? The one that is hosted on GitHub? At http://tableau.github.io/webdataconnector/Examples/GoogleSheetsConnector.html?

**Comment by lbrendanl** [comment]
I am closing Google Sheets related issues.  We are releasing a native connector to Google Sheets in Tableau 10.0.  More info here: http://www.tableau.com/about/blog/2016/5/connect-directly-your-google-sheets-tableau-10-53954

We will not be supporting the WDC version of the Google Sheets connector.  It will of course still be available for use! We will not move the hosted version as to not break existing connections, and the connector code itself will remain available.
