### ISSUE TITLE
Tableau -SharePoint Connection

### ISSUE THREAD

**Issue by natashasweety7** [tableau/webdataconnector#230]
Hi all,

I have created a connection to my sharepoint 2010 lists

[tableau ](https://mindmajix.com/tableau-training)filters the data according to the list's default.

the default is created because i want each of my employees to see only their documents.

when i build a dashboard for my CEO i want him to see all data

does anyone know a quick bypass?

Thanks
Natasha

**Comment by lbrendanl** [comment]
Hi @natashasweety7,

Is this the native sharepoint lists connector in Tableau? Or a custom web data connector that connects to sharepoint lists?  This github repo is targeted at the developer tool and API of the web data connector platform so we will not be able to help much with specific connectors that we didn't build.  I would suggest opening a ticket with the Tableau Support team.

Thanks,
Brendan

**Comment by SPGally** [comment]
HI Natasha,

Check this is a quick approach to [report on SharePoint lists and libraries in Tableau](http://www.axioworks.com/2018/02/using-tableau-to-report-on-sharepoint-lists-and-libraries-a-step-by-step-guide/)

Regards,
Paul.
