### ISSUE TITLE
Call getSchama multiple times/dynamically

### ISSUE THREAD

**Issue by welkinlan** [tableau/webdataconnector#231]
Hello,

I have a use case where I only want to populate the schema when the user drags/uses a table. The reason being our schema discovery for data sources is very time consuming.

Is there a way to implement this behavior? (call getSchama() & update schema multiple times/dynamically)

Another question is how could I include more user inputs (for e.g., custom query, etc.) after the initial interactive phase? Like invoking interactive phase programmatically to incorporate more user inputs?

Thanks,
Tian

**Comment by welkinlan** [comment]
Or another way to ask: is there a way to update Table.tableInfo.columns?
In the API, it says 
```
/** @member {Object} Information about the table which has been requested. This is
       guaranteed to be one of the tables the connector returned in the call to getSchema. */
      this.tableInfo = tableInfo;
```

**Comment by lbrendanl** [comment]
Hey @welkinlan,

Unfortunately there is not a way to do what you are asking with regards to dynamic schemas.  The only way it can be  updated is if the user edits the connection and your WDC has the chance to reload.  

There also isn't any support for additional interactions by the user after the interactive phase has concluded.  So you'll need to gather everything up front.  I'll pass your request on to the PMs on my team though.

Thanks,
Brendan

**Comment by welkinlan** [comment]
Hi @lbrendanl, thanks for your answer.

Could you be more specific on "The only way it can be updated is if the user edits the connection and your WDC has the chance to reload."

Thanks,
Tian
