### ISSUE TITLE
Incompatible type of argument(s) in call to api()

### ISSUE THREAD

**Issue by craigbloodworth** [tableau/webdataconnector#235]
When connecting to https://www.tableaumapping.bi/wdc/legacy using Desktop 10.3.5 the schema phase works just fine however getting data results in the following error:

Error: incompatible type of argument(s) in call to api(); candidates were api(QString,QVariantList) file: https://www.tableaumapping.bi/wdc/js/tableauwdc-2.1.latest.min.js line: 2

Anybody seen this before? Any work arounds or obvious issues?

**Comment by craigbloodworth** [comment]
Managed to solve the issue. The code was returning invalid data to the WDC, strings where int and float values should be.

Would be nice to have a more descriptive error @lbrendanl

**Comment by xmikew** [comment]
Googling for this exact error shows exactly one result. This issue. You also get this vague error if you forget to pass an array to schemaCallback().
