### ISSUE TITLE
getSchema not getting invoked

### ISSUE THREAD

**Issue by scmarlatt** [tableau/webdataconnector#238]
I seem to be running into an issue where getSchema is not being invoked after calling submit(). I added some logging statements to my application, and am looking into my tableau log files and seeing that the log immediately before submit is printing, and then the log statement in the first line of getSchema is not being logged.

I'm also seeing this right after clicking submit, even though I do have a connectionName
"No data supplied for tableau.connectionName. Using default caption."

**Comment by scmarlatt** [comment]
It seems like the gather data phase is never getting kicked off. If anyone has experienced this in the past and has any ideas on why it may be happening, please let me know.

**Comment by dcarr45** [comment]
Hey @scmarlatt , did you ever figure this out? Having the same problem

**Comment by sagarpatel8384** [comment]
Was there a resolution here? I'm running into the same issue.

**Comment by contra** [comment]
Hmm, I'm having the same issue but don't have any authentication on this page. The connector was just working fine and now suddenly exhibits this issue with no changes on our end. Did anyone find a resolution to this / a way to debug it further than just looking at the logs?

**Comment by contra** [comment]
Pretty sure this is related to the other ready state issue - adding a `window._tableau.triggerInitialization()` after creating and registering the connector fixed this for me.

**Comment by scmarlatt** [comment]
@dcarr45 @sagarpatel8384 @contra - Sorry for giving no response. This was never resolved as I stopped working on the project shortly after creating this
