### ISSUE TITLE
Web Data Connector issue with integer range when refreshing

### ISSUE THREAD

**Issue by gettosreejith** [tableau/webdataconnector#240]
Hi,

I have a WDC setup and it loads a numerical column in the database. When loading initially, it works fine, but when refreshing, the integers above 32767 is getting changed. It looks like it's overshooting the 16 bit integer range (-32768 to 32767). So 32768 becomes -32768, 32769 becomes -32767 etc. Any idea how to resolve this.

A few samples listed below
**Actual | Corrupted**
32778 | -32758
32849 | -32687
32852 | -32684
32859 | -32677
32984 | -32552

**Comment by benlower** [comment]
@gettosreejith thanks for posting this. we are looking into this.

**Comment by ashwinar** [comment]
@gettosreejith Looked into the issue. I used the example incremental refresh connector ( found at \Examples\html\IncrementalRefreshConnector.html ) and loaded 30000 initially and refreshed data until 90000. I didn't notice any integer overflow. Can you take a look at the example provided and see if you can tell how it differs from what you are doing? Thanks!

**Comment by ashwinar** [comment]
meant to leave open until I hear back from @gettosreejith

**Comment by gettosreejith** [comment]
Hi @ashwinar,

Thanks for looking into this. This one completely fell off my radar. Let me recollect on this and will get back to you.
