### ISSUE TITLE
tableau.abortForAuth() or abortWithError() does not trigger any error message on Tableau Desktop

### ISSUE THREAD

**Issue by sonali-parija** [tableau/webdataconnector#243]
I have a WDC page which makes an api call with a secure token .All works well until the token expires.  
When it expires, In my connector, during data extract it receives “HTTP Error 401. – Unauthorized”, to which I am calling tableau.abortForAuth() so that the user is prompted for entering valid token again.
This works as expected on WDC simulator it triggers an error message and relaunches the application. But when used on Tableau Desktop , on clicking of Update Now, the ‘Loading Data ’ message is displayed for indefinite period and it does not trigger any error message nor re-launches  the connector page again for re-entering the token.

The second issue is with “tableau.abortWithError()” when used in WDC page for the scenario where a 404 error response is received from an api fetch call.
The error message gets triggered when running on WDC simulator but nothing appears on Tableau Desktop.

I am using Tableau Desktop  10.5.2 version and below is a simple example of a WDC page with both the scenarios. 
https://github.build.ge.com/gist/anonymous/10d504eaed92a89c8a6ff24823364dc0

**Comment by brianjjohnson** [comment]
Any follow-up on this. I am having a similar issue. abortForAuth() does not relaunch the application with the phase set to auth. Instead I just get the following error:

![image](https://user-images.githubusercontent.com/6231961/39377298-9fcaa9ea-4a22-11e8-9cb6-3aaa17ce842b.png)

**Comment by lukelasich** [comment]
I'm having this exact same issue. When trying to enter auth phase through abortForAuth() I just seem to get an error message. Either the error message I specify when calling abortForAuth("XXX") or if I call it without any parameters I get an "invalid username or password" message as seen above with the text: "no details available".

I'm calling abortForAuth when the phase is gatherDataPhase and the user is not authenticated.

**Comment by kanstantsin-chernik** [comment]
Having the same issue. Simulator relaunches in auth phase while Desktop app just shows the error

**Comment by xli1000** [comment]
I am still having this problem. Can you re-open it? When I call `abortForAuth`, an error message is shown, but the connector is not re-launched in auth mode. I am calling it in `init`.
