### ISSUE TITLE
SSO Support for WDC

### ISSUE THREAD

**Issue by sunil-v** [tableau/webdataconnector#245]
Hi,
Does WDC support SSO? We have an issue where a user sees a login screen when opening a WDC URL from Tableau Destkop. Please see the issue description.

**Issue:** 
When trying to connect to a WDC URL from Tableau Desktop, a login screen is shown. (The WDC URL is generated by our web application)

**Workflow:** 
1. A user logs into our application using SSO
2. Generates the WDC URL from our application.
3. Copies the URL, and connects to it from Tableau Desktop.
4. Tableau Desktop opens a browser and shows the login screen.

Thanks

**Comment by bmvr** [comment]
An news on this?
