### ISSUE TITLE
[Question] Can I create a WDC that proxies an API?

### ISSUE THREAD

**Issue by loganpowell** [tableau/webdataconnector#248]
Question from the Census Bureau (one of your biggest fans):

We're about to build a number of WDCs and have a couple of questions that I can't find (easily) after searching your docs (great tutorial btw!):

1) Can we create a WDC that basically just serves as a proxy for an API. I.e., I'm thinking of using something like `window.location.pathname` to get a REST URL, which would be passed into some logic that would call an API and send the request through the Tableau WDC library functions. Is this possible?

2) If that's cool, would it be safe to add the key into the URL of the WDC instead of using an interactive prompt? Would that be stored as part of the URL so it could be refreshed when loading the file?

3) Also, as this would be a pass-through, we wouldn't exactly be able to explicitly set `getSchema`, is there any precedent for something like this? In any case, might you have some guidance?

**Comment by KeshiaRose** [comment]
Hi Logan,

I don't immediately see any reason why you couldn't do what you are proposing but I would love to hear more about it. Feel free to email me at krose@tableau.com and I would be glad to chat more!

Take care,
Keshia

**Comment by loganpowell** [comment]
@KeshiaRose I figured out how to get the wdc connected with authentication. I believe it would help people if you would - at the very top/beginning of your tutorials/docs - note the age of the browser that's used to read the wdc. That was a point of foreseeable confusion for me.
