### ISSUE TITLE
Examples won't run, error: "Looks like WDC is calling a tableau function before tableau.init()"

### ISSUE THREAD

**Issue by jfitzgerald** [tableau/webdataconnector#25]
I ran into this issue in my local test environment, then verified that it occurs in the hosted examples, too. From this URL: https://tableau.github.io/webdataconnector/Examples/StockQuoteConnector_final.html
Enter a ticket eg. DATA
Click "Get Stock Data"
Observe error in console:
 Looks like the WDC is calling a tableau function before tableau.init() has been called.

This is on a Mac, using Chrome (version 49). I tried an incognito window too, same error.

![stock_quote_connector-error](https://cloud.githubusercontent.com/assets/1093203/14029109/73d0a7e6-f1bd-11e5-8f97-d1c9d1f78a77.jpg)

**Comment by lbrendanl** [comment]
Hey @jfitzgerald,

It looks like you are trying to run the WDC directly in a browser.  This unfortunately won't work.  The WDCs can only be run successfully within Tableau or within the simulator. Try playing with the StockQuotes example from the simulator: http://tableau.github.io/webdataconnector/Simulator/

**Comment by jfitzgerald** [comment]
Makes sense now. Sorry for the false alarm.

**Comment by lbrendanl** [comment]
No need to apologize, definitely not an uncommon thought.  We should try and improve the developer experience here and add some more helpful logging.

**Comment by ParthibanSkava** [comment]
Can't i use like below?

$(document).ready(function () {
    $("#submitButton").click(function () {
           var myConnector = tableau.makeConnector();
           myConnector.getSchema = function (schemaCallback) { };
           myConnector.getData = function (table, doneCallback) { };
           tableau.registerConnector(myConnector);
           tableau.connectionName = "USGS Earthquake Feed";
           tableau.submit();
    });
});
Want to call evreything after the click event.. Based on the button click particular query will execute to fetch data.. 
Why it's throwing error? Can anyone help on this?

**Comment by Arwym** [comment]
I have the same question as @ParthibanSkava . Can't this be done?

**Comment by ataft** [comment]
I also have the same issue. I cannot create the myConnector object and functions until later on, but when I use code like @ParthibanSkava 's, it's throwing this error.

**Comment by lbrendanl** [comment]
Unfortunately, this is not supported by the platform.  The reason for this is that we have some code that runs in our Desktop and Server platforms that need to detect if a given page should be treated as a webdataconnector.  We currently do that by checking to see if a page has registered a connector.  Changing this mechanism would require some work on the platform side unfortunately, so no quick fix. 

Could you describe a bit more to me about what your trying to accomplish?

**Comment by ataft** [comment]
I don't want to set the getSchema and getData functions when the "https://connectors.tableau.com/libs/tableauwdc-2.2.latest.js" script is loaded because I'm allowing users to select tables/fields and then generate data using the UI. Is there a way to register the connector when the page loads, but then set or change these functions later?

**Comment by sistasi** [comment]
hi, how to test whether the connector is working properly then? 
i tried to create a connector however it's taking ages to load the data...

**Comment by johnfkraus** [comment]
> Hey @jfitzgerald,
> 
> It looks like you are trying to run the WDC directly in a browser. This unfortunately won't work. The WDCs can only be run successfully within Tableau or within the simulator. Try playing with the StockQuotes example from the simulator: http://tableau.github.io/webdataconnector/Simulator/

If so, can the tutorials be updated to reflect this.?

**Comment by johnfkraus** [comment]
> Hey @jfitzgerald,
> 
> It looks like you are trying to run the WDC directly in a browser. This unfortunately won't work. The WDCs can only be run successfully within Tableau or within the simulator. Try playing with the StockQuotes example from the simulator: http://tableau.github.io/webdataconnector/Simulator/

The tutorial directly contradicts your advice: "You can now test OAuth sign-in by starting the local web server. The web server uses Node.js and the Express framework. You can do this test in the browser without using the simulator that is part of the Web Data Connector SDK."  Is the tutorial wrong?
https://tableau.github.io/webdataconnector/docs/wdc_oauth_tutorial.html
