### ISSUE TITLE
Web dataconnector is not loading data in tableau 10.4

### ISSUE THREAD

**Issue by tandonakash** [tableau/webdataconnector#252]
I have created one WDC which is getting data from REST API. It's working in the simulator but not able to load data in the tableau desktop version

**Comment by KeshiaRose** [comment]
Hi @tandonakash,

Have you tried debugging using the [built-in debugger](http://tableau.github.io/webdataconnector/docs/wdc_debugging#debugging-tableau)? Since WDCs use a different browser than what you are probably using to run the Simulator there can sometimes be breaking differences when you try to use your connector in Desktop. Using the built-in debugger can help you find those differences that could be causing problems in your WDC.

Take care,
Keshia

**Comment by JyothirmaiT** [comment]
Hi Keshia,
I have a similar issue, my WDC works well with simulator also connects to tableau but when I hit upload it keeps on showing loading screen but data never shows up. I also tried debugger but even debugger hangs after ajax request. I so tired of this problem, please help!!
Thank you!

-Jyothirmai

**Comment by deytalytics** [comment]
Same here and my WDC worked fine on 10.2. Seems to be a problem with supporting XMLHttpRequest in JavaScript.

**Comment by contra** [comment]
Anyone ever figure this out? Same issue - debugged to the point where it sends an HTTP request then it takes a crap (debugger hangs until it crashes, no data comes into tableau).

**Comment by eboebo** [comment]
I've been experiencing this issue for months! Data loads not problem in the simulator but won't work in Desktop.

**Comment by JyothirmaiT** [comment]
> I've been experiencing this issue for months! Data loads not problem in the simulator but won't work in Desktop.

This might happen because of CORS. Please check if the server where you are hosting WDC is CORS enabled.

**Comment by devstudio77** [comment]
> I've been experiencing this issue for months! Data loads not problem in the simulator but won't work in Desktop.
> 
> Update: It is because I was using nested ajax calls. The first one authenticates and pulls out the access token for the nested call. I am able to get around this so I will just update my code to include one request.

Hi eboebo, I have exactly the same issue. Could you provide an example of your code please? I mean how to include 2 calls (post and get) into one. Many thanks in advance
