### ISSUE TITLE
Redirecting to the SSO URL instead of WDC (html) in gatherData Phase

### ISSUE THREAD

**Issue by hmrasi** [tableau/webdataconnector#254]
Hi,
          I have a web data connector which im using the web services. And those web services are using the OAM(SSO) authentication. I have configured the OAM to redirect directly to my code after authentication. It worked fine and im able to register the connector with my code and complete interaction phase as well.

Now, when im submitting data to Tableau, again my code has to run to get the schema and data. But, the path tableau is storing is the html file and again it is redirecting to OAM not to the code. So tableau is going to hang at that particular area. 

As i already logged into the OAM, If Tableau stores the OAM related credentials, then it will work. But it's not storing.

Initial URL : http://eaa...:7777/tab-wdc

It will redirect to the URL : http://eaa...:6012/OAM/login?token

after giving credentials it will redirect to URL :  http://eaa...:7777/tab-wdc.html
..
Now, in the gatherdataPhase it is hanging at the URL http://eaa...:6012/OAM/login?token not redirecting to html page ..

Any help on the issue?
Thanks a ton in advance.

Thanks,
hmrasi

**Comment by rcbeeler** [comment]
Is the tableau.submit() being called automatically or in some part between the 2nd page or the 3rd you listed above? I've experienced the gather data phase loading the url wherever the browser was sitting. For example, if the 3rd page hasn't finished loading, it will be handled asynchronously and the http://eaa...:6012/OAM/login?token page might still be the URL at the time of submit. I've tested this using a tableau.log(location.hostname) just before submit, or in some other relevant place.

**Comment by bmvr** [comment]
Hello, any updates on this? I'm getting crazy on the same issue.

**Comment by hmrasi** [comment]
@bmvr ,

The application which we are trying to authenticate have the SSO authentication and we found a way to bypass the SSO login, so, we were able to do that without redirection

**Comment by bmvr** [comment]
But this bypass you did because you could manage a way to bypass it on your side right? There is nothing to do in the Tableau js library right?

I was just wondering if there is a way that I could fetch some information like a cookie or something in the Interactive phase that would help me on the data gathering phase.
Because basically I need a SessionID and a XSRF-TOKEN in order to bypass my SSO.
