### ISSUE TITLE
authPhase + tableau.connectionData

### ISSUE THREAD

**Issue by recnaleerf** [tableau/webdataconnector#255]
When you use `authType = custom` or `authType = basic`, the examples show that you can change the UI accordingly to show/hide items as needed. However, since the authPhase replaces the InteractivePhase, any changes to `tableau.connectionData` doesn't seem to get updated because the authPhase only allows for username and password to change.

I need to be able to Pass Data Between Phases, as per documentation https://tableau.github.io/webdataconnector/docs/wdc_phases#pass-data-between-phases

in a system that utilizes a session/basic auth.

How does one pass data between phases that are required user interaction when using authentication?

**Comment by tagyoureit** [comment]
Check this [doc](http://tableau.github.io/webdataconnector/docs/wdc_phases.html#pass-data-between-phases).
