### ISSUE TITLE
what is the plan to support live data instead of only creating only an extract?

### ISSUE THREAD

**Issue by changleicn** [tableau/webdataconnector#26]
web data connector is really a nice feature. But currently it is limited to an extract, so it does not work for large data set.

what is the plan to support live data?

**Comment by lbrendanl** [comment]
Hey @changleicn,

Currently we don't have any immediate plans to support live data, at least not in the same way that we support live data for other data sources (like SQL Server), where we issue all queries directly to the data base.  We are exploring ways to make web data connectors more responsive and better suited for large data sets.

What is you use case and volume of data?  Would being able to pass some sort of parameters between Tableau and your web data connector help?

Appreciate the feedback.

**Comment by changleicn** [comment]
@lbrendanl Thanks for your response. There is a feature request on Apache HAWQ to provide a Rest API (https://issues.apache.org/jira/browse/HAWQ-319). So we are thinking wether BI tools can use HAWQ Rest API and also combine data from different systems.

**Comment by yurifal** [comment]
@changleicn Why not just use Pivotal Greenplum live connection in Tableau? 
It allows connecting live to HAWQ datasources as well.

Yours,
Yuri

**Comment by changleicn** [comment]
@yurifal yes, i know that odbc works :-). This is another way to connect to HAWQ when HAWQ is only exposed to external as a REST service. 

I think this feature might replace the old protocols (odbc) in future since there are so many new data sources and new database systems, and developing the odbc protocols for different platforms is much more difficult than the web connector way. 

Really like this feature. Looking forward to see webdataconnector for live data.
