### ISSUE TITLE
Issue with WDC Simulator

### ISSUE THREAD

**Issue by Giridhar-enukurthi** [tableau/webdataconnector#262]
Hi Team,

I have followed all instructions as recommended in the documentaion for installing the WDC Simulator.

But getting the below error whn I am trying to test it. Please see the command response below.

c:\test\wdc>**npm install --production**
npm WARN notice [SECURITY] hapi has the following vulnerabilities: 1 high, 2 moderate. Go here for more details: https://nodesecurity.io/advisories?search=hapi&version=9.5.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] moment has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=moment&version=2.11.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] call has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=call&version=2.0.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] moment has the following vulnerabilities: 1 moderate, 1 low. Go here for more details: https://nodesecurity.io/advisories?search=moment&version=2.10.6 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] content has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=content&version=1.0.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] ecstatic has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=ecstatic&version=1.4.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm notice created a lockfile as package-lock.json. You should commit this file.
added 121 packages, removed 447 packages and moved 29 packages in 45.603s

c:\test\wdc>**npm start**
module.js:549
    throw err;
    ^

Error: Cannot find module 'c:\test\wdc\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
module.js:549
    throw err;
    ^

Error: Cannot find module 'c:\test\wdc\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

c:\test\wdc>

**Comment by espressobeanies** [comment]
I get something different: https://github.com/tableau/webdataconnector/issues/282

**Comment by chenteng2016** [comment]
Thanks for pointing out the security vulnerability issue and contributing to webdataconnector!

As for security vulnerabilities:
As discussed with Nick (theoutlander), our recent update focus on fixing security vulnerabilities rather than updating all packages to the latest ones. WDC 3.0 framework will also be available in the short future!

As for npm start issue:
We recently finished some migration works, please considering updating your node version and check the latest master branch again, thanks.

Please help check if the latest master works fine in your environment, thanks again!

**Comment by chenteng2016** [comment]
Please help reopen if there is still an issue. Thanks for contributing to webdataconnector!
