### ISSUE TITLE
Unable to access localhost : npm start failed

### ISSUE THREAD

**Issue by suniltikar** [tableau/webdataconnector#263]
Hello Team,

This might be a stupid question but here is what I am getting-

![image](https://user-images.githubusercontent.com/20704119/42783924-7c1fdd34-891b-11e8-9068-8e9528209fc0.png)

I installed npm and when I did npm start below is the error I received -

$ npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xx44079\AppData\Roaming\npm-cache\_logs\2018-07-16T21_19_03_748Z-debug.log

below is log file -

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose stack Error: **missing script: start**
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:402:5
4 verbose stack     at handleExists (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:366:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:312:19)
5 verbose cwd C:\Program Files\nodejs\node_modules\npm\lib
6 verbose Windows_NT 6.1.7601
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 verbose node v8.11.3
9 verbose npm  v5.6.0
10 error missing script: start
11 verbose exit [ 1, true ]

Kindly assist.

Regards,
Sunil

**Comment by suniltikar** [comment]
Could anyone please assist on this issue?

**Comment by chenteng2016** [comment]
@suniltikar were you able to serve the simulator locally now? Please make sure you clone the code to local [link](https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository) and then run commands within the project directory.

**Comment by chenteng2016** [comment]
Please help reopen if there is still an issue. Thanks for contributing to webdataconnector!
