### ISSUE TITLE
Communication with the Tableau Protocol Server process was lost

### ISSUE THREAD

**Issue by almarcotte** [tableau/webdataconnector#265]
Hello,

I created a WDC that fetches data being streamed from a REST endpoint. The interactive step asks a few questions to the user then sends a POST to an endpoint followed by a GET to another endpoint, the latter returning the results as a stream.

For smaller result sets, it generally works without any issues although it is sometimes a bit slow. I'm now testing with larger data sets and getting the following error:

> Tableau failed to create an extract. This data source requires an extract before you can start your analysis.
> 
> Click Edit Data Source, and then click the sheet tab to create the required extract.
> 
> Click Continue to proceed without creating the required extract.
> 
> An error occurred while communicating with data source 'My WDC Connection'.
> 
> The connection to the data source might have been lost.
> 
> ReadBytes: Communication with the Tableau Protocol Server process was lost.
> 
> Unable to create extract
> 
> No details available.
> 

For reference, if I bypass the WDC and manually go fetch the result set, the file contains ~14 million rows with 11 columns. The columns (for this sample) are all typed string although some of them represent numerical value.

Beside the error above (which I get in Tableau as a popup after about 20-25 minutes) the logs don't display any error. The tabprotosrv.txt file has millions of lines like this:

```
{"ts":"2018-07-24T15:28:51.242","pid":65167,"tid":"a8748","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"web-data-connector","v":"Looking for table id 'my_wdc_table'. Number of tables is 1","ctx":{"client-type":"desktop","procid":"65040","tid":"688821","version":"20181.18.0706.1237"}}

{"ts":"2018-07-24T15:28:51.242","pid":65167,"tid":"a8748","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"web-data-connector","v":"Next id is 'my_wdc_table'","ctx":{"client-type":"desktop","procid":"65040","tid":"688821","version":"20181.18.0706.1237"}}

{"ts":"2018-07-24T15:28:51.242","pid":65167,"tid":"a8748","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"web-data-connector","v":"ReadRows: numrows='1'","ctx":{"client-type":"desktop","procid":"65040","tid":"688821","version":"20181.18.0706.1237"}}

{"ts":"2018-07-24T15:28:51.242","pid":65167,"tid":"a8748","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"web-data-connector","v":"Done reading rows. Valid Data = 1","ctx":{"client-type":"desktop","procid":"65040","tid":"688821","version":"20181.18.0706.1237"}}
```

Is there any way I can troubleshoot this any further? I should mention this is entirely on Tableau Desktop. The WDC is also running as a Javascript application locally but I ran into the same problem deploying it on AWS.

**Comment by drjuarez** [comment]
Hello, is there an update on this? I am running into a similar issue.  My data size is relatively small < 100mb.

**Comment by maxrandolph** [comment]
Going to close this as it's quite an old issue and we'll need more details to determine what's going on. If this is still an ongoing issue, please reopen a new issue and we can look into what's happening.
