### ISSUE TITLE
Webdataconnector fails for large data

### ISSUE THREAD

**Issue by tapassingh** [tableau/webdataconnector#272]
I have a data source (REST API), which have arround 300000 records, I am extracting data page wise, but tableau fails to create extract of it. Below is the log details, I am not able to understand anything from this, if someone can help me, that will be great.

> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000007FEB99FF43E tabdoc!CommandsController::DoOne"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000007FEB99FF78F tabdoc!CommandsController::DoOne"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000007FECB5C5834 tabui!CreateCommandParams::SetAccountsDimension"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000007FECB87722E tabui!RecentFileList::SetFolder"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000000006275FB86 Qt5Widgets!QWidget::event"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000000006284BBD7 Qt5Widgets!QFrame::event"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x0000000063C444CD Qt5Core!QCoreApplicationPrivate::sendThroughObjectEventFilters"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x00000000627367CC Qt5Widgets!QApplicationPrivate::notify_helper"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x0000000062734B2C Qt5Widgets!QApplication::notify"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000007FECB73E4BF tabui!TApplication::notify"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x0000000063C42529 Qt5Core!QCoreApplication::notifyInternal2"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x0000000062737B11 Qt5Widgets!QApplicationPrivate::sendMouseEvent"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000000006277A06D Qt5Widgets!QSizePolicy::QSizePolicy"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x0000000062777ED3 Qt5Widgets!QSizePolicy::QSizePolicy"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x00000000627367E0 Qt5Widgets!QApplicationPrivate::notify_helper"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x0000000062735D26 Qt5Widgets!QApplication::notify"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000007FECB73E4BF tabui!TApplication::notify"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x0000000063C42529 Qt5Core!QCoreApplication::notifyInternal2"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000007FEDBAA1B0C Qt5Gui!QGuiApplicationPrivate::processMouseEvent"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000007FEDBAA4070 Qt5Gui!QGuiApplicationPrivate::processWindowSystemEvent"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000007FEDBA884EC Qt5Gui!QWindowSystemInterface::sendWindowSystemEvents"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x0000000063C87A35 Qt5Core!QEventDispatcherWin32::processEvents"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x0000000077149BBD USER32!TranslateMessageEx"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x00000000771498C2 USER32!TranslateMessage"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x0000000063C871B9 Qt5Core!QEventDispatcherWin32::processEvents"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000007FEBFF0A029 qwindows!qt_plugin_query_metadata"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x0000000063C3EEF1 Qt5Core!QEventLoop::exec"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x0000000063C41387 Qt5Core!QCoreApplication::exec"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000007FECB73D722 tabui!TApplication::LaunchUI"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000007FECB73E1E4 tabui!TApplication::Startup"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000000013F523877 tableau!TApplication::Startup"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000000013F59E085 tableau!TApplication::Startup"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000000013F59D97D tableau!TApplication::Startup"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x00000000770259CD kernel32!BaseThreadInitThunk"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"stack walk","v":"0x0000000000003d64 0x000000007728383D ntdll!RtlUserThreadStart"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"fatal","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"msg","v":"End of call stack for LogicAssert"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"3d64","sev":"warn","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"msg","v":"NotifyOfException::TableauException"}
> {"ts":"2018-10-10T08:58:07.556","pid":13692,"tid":"49c4","sev":"info","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"ec-store","v":{"cns":"AQTV4Z","elapsed-ms":"98","key-hash":"956312811","key-size-b":"82","load-time-ms":"93","lower-bound-ms":"20","outcome":"done","value-size-b":"27"}}
> {"ts":"2018-10-10T08:58:07.630","pid":13692,"tid":"3d64","sev":"error","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"msg","v":"Error Dialog:"}
> {"ts":"2018-10-10T08:58:07.630","pid":13692,"tid":"3d64","sev":"error","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"msg","v":"**Tableau failed to create an extract. This data source requires an extract before you can start your analysis.\n\nClick Edit Data Source, and then click the sheet tab to create the required extract.\nClick Continue to proceed without creating the required extract."}**
> {"ts":"2018-10-10T08:58:07.630","pid":13692,"tid":"3d64","sev":"error","req":"-","sess":"-","site":"{C60A50EB-AF73-430A-8566-4309F19AB3E7}","user":"-","k":"msg","v":"    Internal Error - An unexpected error occurred and the operation could not be completed."}
>

**Comment by deytalytics** [comment]
Are you sure it didn't just run out of disk space whilst downloading your extract?
