### ISSUE TITLE
Scraping more than 1 year causes error - StockQuoteConnector_final.html

### ISSUE THREAD

**Issue by emdeex** [tableau/webdataconnector#28]
The example WDC works for retrieving Yahoo Finance data for a single stock, for 1 year back.

Modifying line 44 to start back either -2 or -3 years causes the script to fail, with error "no result found for ticker symbol: xxx".

Any ideas why this is so?  The Yahoo finance API appears to support multi-year queries.

**Comment by lbrendanl** [comment]
It seems there is some sort of limit on the API side.  For example, go to the developer console here: https://developer.yahoo.com/yql/console/?q=show%20tables&env=store://datatables.org/alltableswithkeys#h=select+*+from+yahoo.finance.historicaldata+where+symbol+%3D+%22YHOO%22+and+startDate+%3D+%222015-04-01%22+and+endDate+%3D+%222016-04-01%22

The query string select * from yahoo.finance.historicaldata where symbol = "YHOO" and startDate = "2015-04-01" and endDate = "2016-04-01" returns results, but the query string select * from yahoo.finance.historicaldata where symbol = "YHOO" and startDate = "2014-04-01" and endDate = "2016-04-01" returns no results.

I have also seen that specific error ("no result found for ticker symbol: xxx") show up whenever their API is down - which, unfortunately, happens every now and then it seems.

**Comment by emdeex** [comment]
Thanks for looking into this, I'll try Google finance and see if that can
do it...

**Comment by lbrendanl** [comment]
Closing this issue as it appears to be a Yahoo issue as noted above.
