### ISSUE TITLE
WDC shows no data in Tableau Desktop

### ISSUE THREAD

**Issue by Michael-D-R** [tableau/webdataconnector#292]
Hello,

I'm working on a WDC for my company. Everything works perfectly on the simulator, but when I try using it in Tableau Desktop, it looks like no data is being retrieved. The schema is shown correctly but when I click "Update Now", nothing happens. I've tried running it with the debugger but the debugger will simply freeze and become unresponsive (I've left it open for as long as 30 minutes with no luck). I just want to know if anyone has experience with a similar issue. Why would it be working with no issues in the simulator, but then do nothing in Desktop?

Thank you.

**Comment by eboebo** [comment]
I am experiencing the same issue. I was able to download and view my data in Tableau Desktop before I updated to 2018.3. Now I am unable to access it through Tableau.

**Comment by Michael-D-R** [comment]
It turns out the problem was I was using 2 separate ajax calls, but only calling doneCallback() once after both of them. I changed it to call doneCallback() at the end of each ajax call and now it works in Tableau Desktop. As to why my first method was working in the Simulator, but not in Desktop, I am not entirely sure.
