### ISSUE TITLE
DateTime issue for certain locales

### ISSUE THREAD

**Issue by KevinGlinski** [tableau/webdataconnector#297]
I found an issue with datetimes in the web data connector for some locales and can reproduce it pretty easily.  When my laptop is in an english/US locale things work fine, but when i switch to english/Canada then all datetime fields from the WDC return null.

 
![image](https://user-images.githubusercontent.com/5074121/53700156-74406000-3dbd-11e9-8c0a-b866d8cbd9fa.png)

I can reproduce with this simple WDC

```
myConnector.getSchema = function(schemaCallback) {
   var cols = [{
   id: "id",
   dataType: tableau.dataTypeEnum.string
  }, {
   id: "date",
   alias: "date",
   dataType: tableau.dataTypeEnum.datetime
  }];
   var tableSchema = {
   id: "earthquakeFeed",
   alias: "Earthquakes with magnitude greater than 4.5 in the last seven days",
   columns: cols
  };
   schemaCallback([tableSchema]);
  };
 
myConnector.getData = function(table, doneCallback) {
   var tableData = [];
   // Iterate over the JSON object
   for (var i = 0, len = 10; i < len; i++) {
   tableData.push({
   "id":  i + "",
   "date": "2019-02-10 14:31:53.244"
  });
  }
   table.appendRows(tableData);
   doneCallback();
  };
```

It appears that the issue stems from the milliseconds in the time.  When I use "2019-02-10 14:31:53.244" then i get nulls, when strip the milliseconds (2019-02-10 14:31:53), or use just the date (2019-02-10) then they get parsed fine.   I've tested with WDC version 2.2 and 2.3 with tableau 2018.3

**Comment by checkaayush** [comment]
+1

**Comment by illonage** [comment]
Hi,

Tableau Desktop parses dates based on the machine locale. ISO UTC - Timestamp (“2018-10-01T12:01:01.000Z”) can be parsed ONLY when "Local for non-Unicode programs" is set to English (United States). Any other "Local for non-Unicode programs" will return the date as NULL.

Could you check that the setting of the "Local for non-Unicode programs" in Control Panel - Region - Administrative tab.

I hope it is helpful :)
