### ISSUE TITLE
How can we make WDC to work on Apche Tomcat which comes with Tableau server rather than using npm webserver

### ISSUE THREAD

**Issue by anshumanmisri** [tableau/webdataconnector#300]
How can we make WDC to work on Apache Tomcat which comes with Tableau server rather than using npm web server,Can anyone mention what can be done for this.

**Comment by illonage** [comment]
Hi @anshumanmisri, Tableau would not support it. You can find suggestions on how to host your Web Data Connector here: https://tableau.github.io/webdataconnector/docs/wdc_hosting_and_submissions.html

Cheers,
Gigi
