### ISSUE TITLE
Incorrect Join Filtering example

### ISSUE THREAD

**Issue by antoniustefan** [tableau/webdataconnector#303]
The join filtering example shown on this page
http://tableau.github.io/webdataconnector/docs/wdc_join_filtering.html
indicates that the `foreignKey` attribute should be set on the table definition, but the API reference page indicates that it should actually be set on the column definition
http://tableau.github.io/webdataconnector/docs/api_ref.html#webdataconnectorapi.columninfo.foreignKey

**Comment by d45** [comment]
@antoniustefan  Thanks for pointing out this inconsistency.  The join filtering example has been updated. The `foreignKey` attribute must be set on the column, as indicated in the API reference page. The way the example was written would previously throw an exception.  This is no longer the case. 
https://tableau.github.io/webdataconnector/docs/wdc_join_filtering.html
