### ISSUE TITLE
Request to Document Calls

### ISSUE THREAD

**Issue by 1Miguel1** [tableau/webdataconnector#304]
Hello!

I recently worked with a user who was setting up a Web Data Connector and they had the following feedback regarding some documentation that they would like to see added for Web Data Connectors:

_Please document, related to WDC, all website calls made from Tableau products (Desktop, Server, Online, Public) such as but not limited to:
Google Analytics
Tableau*
Etc._

**Comment by illonage** [comment]
Hi @1Miguel1, Can you clarify your feedback, please?
