### ISSUE TITLE
Web Data Connector uses an outdated JavaScript Engine

### ISSUE THREAD

**Issue by loganpowell** [tableau/webdataconnector#305]
First off, I noticed that there are 48 open issues and most of the closed issues in this repository have been closed - seemingly - out of pure hopelessness.

Secondly, Tableau is a very large and well-funded company at this point. The fact that Tableau is still using Qt5 Webkit is surprising to say the least. 

I doubt this issue will get any attention. I've spent two solid days so far trying to debug a relatively simple WDC. 

Very, very disappointing.

**Comment by seanmakesgames** [comment]
Funny you should mention! We are in progress working on the webengine port for QT. Trying to get it available ASAP :D (It's a very high priority for our team)
There are quite a few challenges with the port, and even though our company is larger than it used to be, our team is very small.

New WDCs will be able to be debugged with chrome latest devtools. We'll keep you posted!

**Comment by loganpowell** [comment]
@seanmakesgames great news! Thank you for letting me know. I'll keep the issue open then.

**Comment by rcollette** [comment]
Tableau extensions are debuggable in Chrome with Tableau desktop.   It practically eliminates the need for an emulator.   Very much looking forward to an updated QT environment for the WDC as well.

**Comment by QuarksToQuasars** [comment]
Hi @seanmakesgames ,
is there any timeline on this ? We understand that updating/porting the webengine can be a complex endeavour, however, it would be great if you could share at least a rough roadmap/timeline. Thanks

**Comment by seanmakesgames** [comment]
Unfortunately, no. Our team's work is complete. There are integration / release challenges with the product as a whole which are holding this back. We will try to let you all know as soon as this is on a release train.

**Comment by amit4422** [comment]
Hi guys, we are waiting for the issues to be solved as well. It has been open since quite some time and my customer is waiting for it to get resolved. Any thoughts on getting this prioritized ?

**Comment by d45** [comment]
@amit4422, @QuarksToQuasars, @loganpowell @rcollette  -- You might already know this. The QT WebKit to WebEngine update is available in Tableau 2019.4  - [Web Data Connectors use QT WebEngine browser starting in Tableau 2019.4](https://tableau.github.io/webdataconnector/news/#/2019/11/05/wdc-webengine) 

The debugging process has changed and you can now use the Chrome DevTools. 
* [Troubleshoot WDC WebEngine Issues in Tableau 2019.4 and later](https://tableau.github.io/webdataconnector/docs/wdc_webengine.html)
* [Debugging a WDC in Tableau Desktop 2019.4 (and later)](https://tableau.github.io/webdataconnector/docs/wdc_debugging.html#debug-chrome)

Thanks for reporting the issue (and your patience).

**Comment by loganpowell** [comment]
Woot!

**Comment by loganpowell** [comment]
I can go ahead and close this issue and open a new one if any specific issues arise when we upgrade to 2019.4
