### ISSUE TITLE
Publish as NPM package

### ISSUE THREAD

**Issue by rcollette** [tableau/webdataconnector#308]
It's a heck of a lot easier to check for project dependencies using npm-check-updates or similar, rather than having to monitor blogs or git repos individually.

Having a local instance of the lib also allows for offline development.

**Comment by devstein** [comment]
+1

**Comment by leomao10** [comment]
@illonage What is the plan to do that? And do you need any help for it?

**Comment by theoutlander** [comment]
Since WDC-3 is slated to come out this year, I don't think we will be addressing this issue. In addition, we haven't been making updates to the WDC-2 lib so closing this item.
