### ISSUE TITLE
Cross-Origin Read Blocking (CORB) blocked cross-origin response = Tableau Web Data Connector

### ISSUE THREAD

**Issue by SriniRMTUG** [tableau/webdataconnector#312]
We are trying to pull a JSON structure by invoking an API from the localhost with port number :9097  from Tableau Web Data Connector (Simulator),

The server (node.js) on which Simulator is hosted is on port 8888.  The request is passed from http://localhost:8888/Simulator/index.html to https://localhost:9097/dcj-ors-pc-datawarehouse-sys-api/v1/caseDetails

The chrome browser throws back the below error

Cross-Origin Read Blocking (CORB) blocked cross-origin response https://localhost:9097/dcj-ors-pc-datawarehouse-sys-api/v1/caseDetails with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details. 

![tableau-web-data-connector-issue](https://user-images.githubusercontent.com/51727468/59316361-4d76ad00-8c7b-11e9-838f-f4af90d3f8ef.png)

**Comment by illonage** [comment]
Hi @SriniRMTUG,

Can you check that:
- Your "Content-Type" response header is set as _text/json_
- The Answer from your API (https://localhost:9097/dcj-ors-pc-datawarehouse-sys-api/v1/caseDetails) is not empty
Please?
Cheers,
Gigi

**Comment by illonage** [comment]
No answer, closing the issue
