### ISSUE TITLE
Web Data Connector-Live Data Issue

### ISSUE THREAD

**Issue by rajdhir** [tableau/webdataconnector#317]
Hi Team,

While connecting API's through Web Data Connector in Tableau connection is not established to LIVE nor is allowing to Refresh the data.

Please do provide your inputs on the same.

**Comment by andre347** [comment]
The Tableau Web Data Connector Connection only created an extract of your data. Therefore you don't have a live connection. You can, however, hit the 'Extract Refresh' button to refresh the data and the WDC will fetch new data.

**Comment by rajdhir** [comment]
Extract Refresh Button is showing disabled hence cannot refresh the data as well.

**Comment by illonage** [comment]
Hi - Are you using Tableau Desktop? You can refresh the extract by right-clicking on the data source and select refresh. I hope it helps, Gigi
