### ISSUE TITLE
Updating acquired data with Incremental Refresh

### ISSUE THREAD

**Issue by mchippingtonderrick-afl** [tableau/webdataconnector#319]
Is it possible to update existing rows of data with an [incremental refresh](http://tableau.github.io/webdataconnector/docs/wdc_incremental_refresh)?

For example, if the data being queried is the current status of issues in something like GitHub or Jira, you could want to update the data for the issues that have been updated / modified since the last incremental refresh.

The documentation seemingly only specifies about fetching and appending new data, and does not specify about updating existing data.

**Comment by andre347** [comment]
You need to do a full extract refresh to update existing rows.
