### ISSUE TITLE
Simulator should not have hardcoded Python paths for Windows, and need documentation to run simulator locallt

### ISSUE THREAD

**Issue by mradamlacey** [tableau/webdataconnector#32]
The simulator batch file - `start_server_windows.bat` has hardcoded paths to the Python executable.

I think it should simply require that 'python.exe' is somewhere in the system PATH, and simply invoke it.  No need to look for specific directories.

Alternatively, it could require a `PYTHON_HOME` environment variable be set that gives the location of `python.exe`.

Finally - there does not seem to be any documentation of running the simulator locally.  If this is a supported option, there needs to be some basic instructions on how to use it.

**Comment by benlower** [comment]
@mradamlacey thanks for the feedback. yeah we realized last week the hard coding of the path was very brittle. it worked for a large group of ppl in training but we've seen it fail with other folks. we'll take a look to see how to improve this.

@mpope-tableau can you please take a look at Adam's feedback about doc'ing running the simulator locally?

**Comment by lbrendanl** [comment]
I think what we want is to try the command first without the hard coded value and if that fails give it a try and the hardcoded default location.  Assuming in that script we can someone catch the failure of the first command.

Apologies for the hassle @mradamlacey! We were attempting to make this easier for anyone who didn't have their path configured correctly but inadvertently made it much more difficult for some.

**Comment by jdomingu** [comment]
We've updated the dev branch to use an npm http-server package instead to avoid these platform compatibility issues. We've also added some docs [here](http://tableau.github.io/webdataconnector/docs/). Thanks!
