### ISSUE TITLE
Incremental refresh not working with datetime incrementColumn in incrementalRefresh example

### ISSUE THREAD

**Issue by checkaayush** [tableau/webdataconnector#320]
Edit:
Issue https://github.com/tableau/webdataconnector/issues/297 is similar to what I'm observing for incremental refresh.

When increment column is of type datetime, incremental refresh doesn't work on Tableau Desktop 2019.2.x.

**Comment by illonage** [comment]
Hi @checkaayush,

Is it for a specific local?

**Comment by illonage** [comment]
No answer, I am closing it. Feel free to re-open it if it is still an issue for you
