### ISSUE TITLE
Tableau Desktop browser using authentication loses session 

### ISSUE THREAD

**Issue by annenokia** [tableau/webdataconnector#326]
Hello,
 
I have created a Web Data Connector, that was working fine before implementing authentication. After authentication has been implemented, it stopped working, because when the second phase starts, a new clean session is created with a new session thus the old session is lost and the user is not authorized. Also it works fine on the simulator (with authentication), and I am running Tableau Desktop for Windows, version 2012.2.3 (latest as of now). 
 
Please see the attached simple example and screenshots on the community forum discussion I had:
https://community.tableau.com/thread/313634
 
Thanks,
Anne

**Comment by illonage** [comment]
Hi @annenokia - can you share your code for authentication, please?

**Comment by illonage** [comment]
No answer, I am closing this issue
