### ISSUE TITLE
Tableau WDC data is Not Loading

### ISSUE THREAD

**Issue by aartihande** [tableau/webdataconnector#332]
Trying to load the JAMF data into the tableau desktop,
I have created the connection with tableau. But data is not loading .
![WDC](https://user-images.githubusercontent.com/31095820/67839254-38f75c00-fb19-11e9-83fe-1017370d3f37.PNG)

**Comment by tansooleng** [comment]
yes i have the same problem

**Comment by illonage** [comment]
Hi - It seems like an issue with the JAMF Web Data Connector, I recommend you reach out to the person that developed the Web Data Connector directly. Cheers, Gigi
