### ISSUE TITLE
Timeout error when trying to refresh a extract

### ISSUE THREAD

**Issue by ivanarielcaceres** [tableau/webdataconnector#338]
I would like to report an issue when extracting from the Tableau Server using the WDC connector.

1. It works correctly when using the simulator.
2. It works correctly when used from the tableau desktop.
3. Fail to schedule the extraction from the server.

We have published the data source to the server and we've also scheduled the extraction.

The configurations made on the server was based on the help guide [1]:

1. We have added the following URLs to the white list using the command.

`tsm data-access web-data-connectors add http: //SERVERNAME/Examples/html/sdeint_Connector.html`
`tsm data-access web-data-connectors add http://SERVERNAME:80/Examples/html/ sdeint_Connector.html`
`tsm data-access web-data-connectors add http://SERVERNAME/Examples`
`tsm data-access web-data-connectors add http://SERVERNAME: 80/Examples`

2. We have double check that the URLs were added to the whitelist.
`tsm data-access web-data-connectors list`

3. We have configured the following:
`tsm data-access web-data-connectors allow -r true`

After all, it always gives an error related to Timeout.

Following a snippet of the log file:
`status = ExtractTimingFailure | jobId = 2306679 | jobLuid = c2052450-827b-4b86-bb98-b035eb504b2d | siteName = "SIGG" | datasourceName = "SSM WDC Reports" | refreshedAt = "2019-10-14T12: 19: 00.245Z" | session = 06A927CDEA564D78B03BA3BA1D1E255C-1: 1 | scheduleName = "Run now refresh" | scheduleType = "FullRefresh" | jobName = "Refresh Extracts" | jobType = "RefreshExtracts" | totalTimeSeconds = 28855 | runTimeSeconds = 28851 | : 46: 16.595Z "| startedTime =" 2019-10-18T16: 46: 21.318Z "| endTime =" 2019-10-19T00: 47: 12.358Z "| correlationId = null | priority = 0 | serialId = 505913473 | extractsSizeBytes = 0 | jobNotes = "Operation cancelled.
The task was canceled. Tableau can not conclude the task of updating extracts, exceeding the time limit. Posibles reasons: a large data source, a network connection is slow, there are not enough resources available, on the server or the external data base. <a href='https://kb.tableau.com/articles/Issue/error-extract-timeout-7200-seconds?lang=pt-br'> Read more </a>`

We have checked all these items and all seems to be ok.

Notes: 
1. We have acquired a JIRA plugin called AIO Tableau connector for Jira [2]  and configured its URL as reliable and it's works correctly.
2. The test was done using the examples in this repository.
3. The tableau server version is 2019.3.0 (20193.19.0913.2225) 64bits Windows

[1] - https://help.tableau.com/current/server/en-us/datasource_wdc.htm
[2] - https://marketplace.atlassian.com/apps/1214641/aio-tableau-connector-for-jira

**Comment by illonage** [comment]
Hi @ivanarielcaceres - Did you try to refresh the extract on an instance of Tableau Desktop installed on the same machine that is running Tableau Server? 

When an extract is failing on Server, can you go to Site Status > Background Tasks for Extracts and can you share with me the error message there, please?

**Comment by ivanarielcaceres** [comment]
Thanks @illonage, we will try it.

**Comment by venkatamanikanta-b** [comment]
I connected Tableau public API through Web Data Connector in Tableau desktop, but it is unable to create extract database in table desktop.
![Screenshot (39)](https://user-images.githubusercontent.com/62616154/77563708-a2707080-6ee7-11ea-9e86-a6f1022a8191.png)

**Comment by illonage** [comment]
hi @venkatamanikanta-b which WDC are you using?

**Comment by venkatamanikanta-b** [comment]
Thank you for your response
I am trying to use tableau public API
Thanks & Regards
Manikanta BV

**Comment by illonage** [comment]
@venkatamanikanta-b, you should reach out to the developer that created this WDC for support. Thanks,
Gigi
