### ISSUE TITLE
connectionData restores after page refresh

### ISSUE THREAD

**Issue by follower90** [tableau/webdataconnector#340]
I keep authentication info in connection data.
And I am implementing logout functionality

Tableau Desktop (2019.4 on Mac) restores connectionData after page refreshed in Tableau Desktop and i become logged in back as a result.
Though it works fine in Simulator.

```
  tableau.connectionData = '';
  window.location.href = '/';
```

**Comment by illonage** [comment]
Hi @follower90,

It is a known issue, I logged it here: https://github.com/tableau/webdataconnector/issues/337
