### ISSUE TITLE
WDC unable to initialize when requested in Desktop-App

### ISSUE THREAD

**Issue by benedikt-brandtner-bikemap** [tableau/webdataconnector#344]
We developed a WDC via the simulator and everything worked fine (Interactive, Authorization, Data-Gathering) but as soon as i load the connector via the Desktop-App (2019.4) on MacOS (mojave 10.14.3) i get a javascript error when the wdc-library tries to initialize:

![image](https://user-images.githubusercontent.com/12509703/72911301-1781c700-3d3a-11ea-824e-6d3b798cf8d7.png)

I used the debugger described here:
http://tableau.github.io/webdataconnector/docs/wdc_debugging.html#debug-chrome

**Comment by illonage** [comment]
Hi @benedikt-brandtner-bikemap 

Can you make that you defined: var myConnector = tableau.makeConnector(); 
Before calling myConnector.init.

If it still doesn't work, can you share your code?

Thanks,
Gigi

**Comment by benedikt-brandtner-bikemap** [comment]
Hey @illonage 

thanks for the quick response :)

this is the initialization function we implemented:

```
export function initWDC(config) {
    docReady(() => {$('#wdc-authorize-button').click(authorize)})

    const connector = tableau.makeConnector()
    const authCode = getCodeParam()

    if (authCode) {
        removeCodeParam()
    }

    connector.init = initCallback => {
        tableau.authType = tableau.authTypeEnum.custom

        // Interactive phase: WDC is called for the first time and form will be shown
        // Auth phase: WDC has already been configured, just showing UI to authenticate again

        if (tableau.phase === tableau.phaseEnum.interactivePhase || tableau.phase === tableau.phaseEnum.authPhase) {
            let accessTokenCall

            // Do we have an authorization code?
            if (authCode) {
                // Get access token and display form
                accessTokenCall = retrieveAccessToken(authCode)

            // Are we already authenticated?
            } else if (tableau.password) {
                const { refreshToken, expires } = JSON.parse(tableau.password)

                // Is the access token expired?
                if (moment().isAfter(expires)) {
                    console.log('has password but is expired')
                    accessTokenCall = refreshAccessToken(refreshToken)
                        .catch(error => {
                            // initCallback must have been called before redirecting
                            initCallback()

                            // We could not refresh the access token, so we need to authenticate again
                            docReady(() => {$('#wdc-authorize-button').show()})
                        })

                } else {
                    // Our access token seems to be valid
                    docReady(config.initForm)

                }
            } else {
                docReady(() => {$('#wdc-authorize-button').show()})
            }

            if (accessTokenCall) {
                // What to do when we have a valid access token
                accessTokenCall
                  .then((tableau.phase === tableau.phaseEnum.interactivePhase) ? () => {
                      docReady(config.initForm)
                  } : () => {
                      // We are in the auth phase, so we submit immediately
                      initCallback()

                      tableau.submit()
                  })
            }
        }

        // Gather data phase: WDC is called without UI to fetch data
        if (tableau.phase === tableau.phaseEnum.gatherDataPhase) {
            const { accessToken, refreshToken, expires } = tableau.password ? JSON.parse(tableau.password) : {}

            // Don't we have an access token?
            if (!accessToken) {
                // Abort and launch UI to log in again

                tableau.abortForAuth()
            }

            // Is the access token expired?
            if (moment().isAfter(expires)) {

                return refreshAccessToken(refreshToken)
                    .then(initCallback)
                    .catch(error => {
                        // We could not refresh the access token, so we need to authenticate again

                        tableau.abortForAuth()
                    })
            }

            // Do nothing here, use password field for authorization
        }

         initCallback()
    }

    connector.getSchema = config.getSchema
    connector.getData = config.getData

    tableau.registerConnector(connector)
}
```
additionally we encountered the error even when we did not override `connector.init`

greets

**Comment by benedikt-brandtner-bikemap** [comment]
@illonage any news about this?

**Comment by illonage** [comment]
Hi @benedikt-brandtner-bikemap 
I will need all your code to help you. You can share it at gzanolli@tableau.com.

**Comment by rrecuero** [comment]
@illonage I am running into the same issue here. What was the solution?

**Comment by illonage** [comment]
hi @rrecuero - Which version of Tableau are you using?

**Comment by rrecuero** [comment]
Thanks for the quick reply @illonage  

`tableauwdc-2.3.latest.js`

I am getting that init of undefined error.

However, I can trigger the initialization manually later if I do:

```
      const DOMContentLoaded_event = window.document.createEvent('Event')
      DOMContentLoaded_event.initEvent('DOMContentLoaded', true, true)
      window.document.dispatchEvent(DOMContentLoaded_event)
```

**Comment by illonage** [comment]
Are you in Tableau Desktop? Does it work in the simulator?

**Comment by rrecuero** [comment]
It works in both if I trigger it manually but the error appears first. I am trying to get rid of it.

It's trying to initialize things before I even call register or anything. Same thing happened here 

https://github.com/tableau/webdataconnector/issues/165

**Comment by maxrandolph** [comment]
Hi @rrecuero, where in your code are you importing the `tableauwdc-2.3.latest.js`?

**Comment by rrecuero** [comment]
script tag inside the `head`

**Comment by maxrandolph** [comment]
Could you share your console log output?

**Comment by rrecuero** [comment]
```
Version Bootstrap is not defined, Initializing SimulatorDispatcher
SimulatorDispatcher.js:19 Initializing message handling
SimulatorDispatcher.js:235 Initializing public interface
SimulatorDispatcher.js:281 Initializing private interface
Shared.js:21 Initializing shared WDC
SimulatorDispatcher.js:191 Received message!
Shared.js:43 null
Shared._errorHandler @ Shared.js:43

(After I trigger the initialization then:)
Shared.js:85 Connector registered
3SimulatorDispatcher.js:191 Received message!
```

**Comment by rrecuero** [comment]
@maxrandolph anything else you need?

**Comment by maxrandolph** [comment]
@rrecuero I think if you're getting a failure in Desktop as well as in the Simulator without the manual initialization being called explicitly, there's likely an issue with the order in which your scripts are being loaded in the `.html` page itself. It's tough to say without seeing more of your code.

Would it be possible to see a stack trace leading up to the error being thrown?

**Comment by rrecuero** [comment]
See screenshot, this.wdc is undefined

![Screen Shot 2020-08-20 at 11 00 16 AM](https://user-images.githubusercontent.com/541599/90808138-672a7000-e2d4-11ea-9539-785a2d22410b.png)

**Comment by theoutlander** [comment]
Is it possible to publish your WDC on codesandbox so we can look at the code and try it out?

**Comment by palakvijay** [comment]
Hello Everyone !!

I am running into the same issue for the upgraded version of Tableau. Our WDC works for till 2019.3 but doesnt work for any version higher than 2019.4.

It would be really helpful if someone can lead me towards solving this.
Thanks in advance.
@illonage @benedikt-brandtner-bikemap

**Comment by theoutlander** [comment]
@palakvijay please take a look @ https://tableau.github.io/webdataconnector/docs/wdc_webengine.html and if it doesn't help, please open a new issue and include your code.
