### ISSUE TITLE
Issues with larger datasets

### ISSUE THREAD

**Issue by bribay** [tableau/webdataconnector#345]
Is there an issue with larger datasets loaded through the WDC? Is there any recommended max dataset size?

I have created a WDC for my project but I am having issues with larger datasets. I have a test dataset with 10K rows and everything loads correctly without any issues. When I increase the size to 100K rows, though, the load process seems to complete correctly but the data does not show. If I increase the size to 1 million rows then the I get an error that the QtWebEngineProcess has crashed. 

Looking through the logs I see that there is a crashdump created for the 1 million row dataset and the actual error is " The thread tried to read from or write to a virtual address for which it does not have the appropriate access."

I am using Tableau Desktop 2019.4. The 100K dataset size is around 100MB while the 1Mill dataset is about 1GB. I have tried loading the data both in debug mode (where you attach the chrome debugger using the instructions at https://tableau.github.io/webdataconnector/docs/wdc_debugging.html) and without launching in debug mode.

Looking through the console logs when the debugger is attached for the 100K file I can see the entire network transfer and everything appears to load correctly. Once it is done, though, headers remain but the data itself never appears. For the 1 million file it takes about 20 minutes for the entire 1 GB to download. When it gets close to the actual file size I the chrome error popup and the debugger window is detached due to the process dying.

**Comment by dorilla** [comment]
Not sure if this is your issue, but I saw this https://github.com/tableau/webdataconnector/blob/5923560682c1030d640366a505cbf51d50fb94ae/docs/wdc_get_data.md

>Note: In Tableau 2019.4 and later, Web Data Connectors use Qt WebEngine as the internal browser. The version of the Qt WebEngine we currently use has a limitation in its data communication channel of approximately 128MB. If your WDC appends more data than can be transmitted at one time, the WDC is created and initialized, but no data is added. To avoid this problem, be sure to insert your data in chunks that are less than 128MB. For more information about this issue, see Troubleshoot WDC WebEngine Issues in Tableau 2019.4 and later.
