### ISSUE TITLE
Why tableau must be register before page created?

### ISSUE THREAD

**Issue by notestyle** [tableau/webdataconnector#346]
Using: https://connectors.tableau.com/libs/tableauwdc-2.3.latest.min.js
I am developing web application on VueJS.

I think tableau wdc connector library needs to be improved or fixed. 

-	The connector.getSchema and connector.getData are needs to be changed after client configure it on web page.
-	I change the connector variables (schema, getSchema) before pageloaded. But “Either invalid data are present or required fields are empty” error shows on the tableau desktop app (from web data connector). I filled all required fields.

Could you please answer below question and describe?
-	Why make registerConnector function must be create when page loading? I wanna register tableau connector after page has already loaded.

<template>
    <v-dialog v-model="dialog" width="500">
        <v-card>
            <v-card-title class="headline">
                <span>API information</span>
            </v-card-title>
            <v-card-text>
                <p class="body-1"><b>NAME: </b>{{info.name}}</p>
            </v-card-text>
            <v-card-actions>
                <v-spacer></v-spacer>
                <v-btn color="primary" :loading="loading" depressed @click="connect">
                    <v-icon>check</v-icon>
                    Connect
                </v-btn>
            </v-card-actions>
        </v-card>
    </v-dialog>
</template>

# created event
created(){
    this.info = Object.assign({}, this.$store.getters.get_tableaudata)
    this.tableauInit()
  },

# Method
methods :{
    tableauInit(){
       var schema = {
        id: this.info.name,
        alias: this.info.name,
        columns: [
            { id: "DATE", dataType: window.tableau.dataTypeEnum.date},
        ]
      }

       var body = { sample: 'sample' }

      // Create the connector object
      this.myConnector = window.tableau.makeConnector();

      // Define the schema
      this.myConnector.getSchema = function (schemaCallback) {
          schemaCallback([schema]);
      };

     that = this
      // Download the data
      this.myConnector.getData = function (table, doneCallback) {
        axios(that.info.url, {
            method: "post",
            data: body,
            withCredentials: true
        })
        .then(response => {
            console.log(response.data)
            var filteredList = response.data.map(function(row){
                return { 
                    categoryId: row.categoryId, 
                    'DATE': row.DATE,
                }
            });

            table.appendRows(filteredList);
            doneCallback();
        })
      };

      window.tableau.registerConnector(this.myConnector);
    },

  connect(){
        try{
            window.tableau.connectionName = this.info.name
            window.tableau.submit();
        }catch(err){
            this.$notify({
                title: "Error",
                text: err.toString(),
                type: "error"
            });
            console.log('ERROR => ', err)
        }
    },

**Comment by sravs9661** [comment]
Tableau Server requires at least one product key that both activates the server and specifies the number of license levels you can assign to users. You can access your product keys from the Customer Portal.

If you need to activate _[tableau training in hyderabad](https://360digitmg.com/tableau-training-in-hyderabad)_ Server on a computer that is offline, see Activate Tableau Server Offline - Adding a License. If you need to activate additional product keys to add capacity to an existing Tableau Server installation, see Add Capacity to Tableau Server
