### ISSUE TITLE
WDC Node.js Proxy with OAuth Tutorial instructions are not correct 

### ISSUE THREAD

**Issue by rushiln** [tableau/webdataconnector#351]
I am trying to use the tutorial found on this page:

http://tableau.github.io/webdataconnector/docs/wdc_oauth_tutorial.html

but under step 2, substep 4 (register your app with four square), the article mentions to "Fill in the Your app name, Download/welcome page url, and Redirect URI(s) boxes." However, when I login to Foursquare and try to make a new application, the page does not come up with these boxes. I've attached an image of what does come up instead. I'm not sure what to put in here as the redirect URL provided does not work. Without this step, I am unable to generate a client secret and client ID that I need to proceed with the rest of the tutorial. Does anyone know what I should enter instead for this tutorial? Are there updated instructions anywhere that I'm missing? Thanks!

![Foursquare new app](https://user-images.githubusercontent.com/61331765/75069455-34d3bd80-54bf-11ea-9540-b667ea9112fc.PNG)

**Comment by Bakulkumar** [comment]
you can fill the app name and App OR company URL with any name and proceed to the next step it will ask you further details like redirect URL.
