### ISSUE TITLE
WDC working in simulator but only loads table info into Tableau desktop (no data)

### ISSUE THREAD

**Issue by christs71** [tableau/webdataconnector#376]
I have set up a WDC to connect to Bitly.  I am able to run and return data without errors on the Simulator, however when I connect via Desktop, it creates the tables but doesn't return data.  I have tried the suggestions already posted in the forums, like chunking the data into smaller pieces and using a cors proxy.  I have spoken with Tableau tech support and they think it might be due to the version of Tableau I am using (2020.1.2).  I have tried to run on both 2019.2 and 2019.3 and it doesn't work.  My question is if I use an earlier version of Tableau, do I also need to use a different version of the web data connector?  Has anyone run into this issue and resolved it?  I have been going around and around on this for several months, so any help would be greatly appreciated.

 I spoke with an engineer at Tableau and this is what she responded:

Thanks again for talking with me about your case yesterday! I went through the logs again and it isn’t clear from the logs why the actual data isn’t being displayed in the UI. The logs show that we render the UI successfully but then we get a close event about a minute later.

2020-05-07T16:02:14.326: 14608-3adc MSG
render-pipeline: Render Start
2020-05-07T16:02:14.328: 14608-3adc MSG
render-pipeline: BeginScene using Qt
2020-05-07T16:02:14.332: 14608-3adc MSG
render-pipeline: Render End
2020-05-07T16:02:14.795: 14608-1820 MSG
Finished rendering sheet: Sheet 1
2020-05-07T16:02:15.552: 14608-1820 MSG
TMainWindow received QEvent::Close

Shortly before the UI render we do see a connection-info-mismatch and this could be what is causing the data to now show up after we render the UI.

2020-05-07T15:59:45.170: 14608-26d0 CONNECTION-INFO-MISMATCH
caption : (MISMATCH) Bitly Data <=> <missing>
:thread-session : (MISMATCH) 4 <=> <missing>
federated-connection : <connection :locale='1024' capti
:locale : (MISMATCH) 1024 <=> <missing>
class : federated
name : (MISMATCH) federated.1fvbdnf0dm78141gpk0ua0 <=> <missing>

Any idea if this is causing no data to be returned and what I can do about it or has anyone had a similar experience and were able to get it to render?

**Comment by illonage** [comment]
Hi @christs71 - Did you try to debug the WDC in Desktop: https://tableau.github.io/webdataconnector/docs/wdc_debugging.html?
