### ISSUE TITLE
Is it possible to get raw json data from url using WDC without creating an html page?

### ISSUE THREAD

**Issue by anh-vuong** [tableau/webdataconnector#392]
I'm trying to get raw data from a URL (https://www.xxx.xxxxx.com/xxxxxxx/api/get-total-count) to connect with Tableau. I created a WDC using this guide: https://tableau.github.io/webdataconnector/docs/ and can get on http://localhost:8888/Simulator/index.html. 

Is it possible to just pull just the raw data from a api url without creating an HTML page?

Thank you,
Anh

**Comment by theoutlander** [comment]
Yes you can. You just need to call the function to get data on document load instead of on button click.

**Comment by anh-vuong** [comment]
@theoutlander thanks for the prompt response! Which part of the code do I modify? The .html file or the .js file? 

https://tableau.github.io/webdataconnector/docs/wdc_tutorial.html

**Comment by theoutlander** [comment]
You would add that code in your js file as per instructions where you add the handler after register connector:

Instead of this:

    $(document).ready(function () {
        $("#submitButton").click(function () {
            tableau.connectionName = "USGS Earthquake Feed";
            tableau.submit();
        });
    });

you can change it to:

    $(document).ready(function () {
            tableau.connectionName = "USGS Earthquake Feed";
            tableau.submit();
    });

**Comment by anh-vuong** [comment]
Where would I put the api url? (https://www.xxx.xxxxx.com/xxxxxxx/api/get-total-count)

**Comment by anh-vuong** [comment]
@theoutlander So far I have the HTML page, the connector object, and the event listening without the button click but now I'm stuck. Can you help? I can create a tableau support ticket.

**Comment by theoutlander** [comment]
Please follow the documentation to create a sample connector. Once you have that working, you should be able to easily modify it to your needs.

**Comment by KeshiaRose** [comment]
Hi @anh-vuong, you will still need an html page to point to but it doesn't need to have anything but your javascript or a reference to your .js file. If you want to run the connector without user interaction you can delete the $(document).ready() section entirely and then add a custom init function before you register the connecter.
```
let myConnector = tableau.makeConnector();

myConnector.getSchema = function (schemaCallback) {
... blah blah blah
};

myConnector.getData = function (table, doneCallback) {
... blah blah blah
};

myConnector.init = function(initCallback) {
  initCallback();
  tableau.connectionName = "My Data";
  tableau.submit();
};

tableau.registerConnector(myConnector);
```
-Keshia
