### ISSUE TITLE
connectioData is Empty

### ISSUE THREAD

**Issue by MinMiguelM** [tableau/webdataconnector#399]
I would like to re open this issue, I am having the same error #144.

When getSchema is called and I get connectionData, it's empty, therefore the getSchema throws an error because it cannot parse the data to JSON.

This error occurs intermittently and I haven't could figure it out if it is a Tableau's error or WDC's error.

I am testing on tableau public 2020.3, on version 2019.2 that error never happened.

Thanks in advance

**Comment by MinMiguelM** [comment]
I added some logs to watch tableau global object.

`{"phaseEnum":{"interactivePhase":"interactive","authPhase":"auth","gatherDataPhase":"gatherData"},"authPurposeEnum":{"ephemeral":"ephemeral","enduring":"enduring"},"authTypeEnum":{"none":"none","basic":"basic","custom":"custom"},"dataTypeEnum":{"bool":"bool","date":"date","datetime":"datetime","float":"float","int":"int","string":"string","geometry":"geometry"},"columnRoleEnum":{"dimension":"dimension","measure":"measure"},"columnTypeEnum":{"continuous":"continuous","discrete":"discrete"},"aggTypeEnum":{"sum":"sum","avg":"avg","median":"median","count":"count","countd":"count_dist"},"geographicRoleEnum":{"area_code":"area_code","cbsa_msa":"cbsa_msa","city":"city","congressional_district":"congressional_district","country_region":"country_region","county":"county","state_province":"state_province","zip_code_postcode":"zip_code_postcode","latitude":"latitude","longitude":"longitude"},"unitsFormatEnum":{"thousands":"thousands","millions":"millions","billions_english":"billions_english","billions_standard":"billions_standard"},"numberFormatEnum":{"number":"number","currency":"currency","scientific":"scientific","percentage":"percentage"},"localeEnum":{"america":"en-us","brazil":"pt-br","china":"zh-cn","france":"fr-fr","germany":"de-de","japan":"ja-jp","korea":"ko-kr","spain":"es-es"},"joinEnum":{"inner":"inner","left":"left"},"authPurpose":"ephemeral","authType":"none","connectionData":"","connectionName":"","language":"en-us","locale":"en-us","logLevel":"info","password":"","phase":"interactive","platformBuildNumber":"20203.20.0801.1333","platformEdition":"public","platformOs":"win","platformVersion":"2020.3.0","propertiesReady":false,"scriptVersion":"","username":"","usernameAlias":"","APIVersion":""}`

There are two properties very weird for me, **phase** and **propertiesReady**, the error happens getting the schema so I thing phase should be gatherData

**Comment by theoutlander** [comment]
tableau.submit changes phase to gatherData
https://tableau.github.io/webdataconnector/docs/wdc_phases.html

![image](https://user-images.githubusercontent.com/749084/90823938-7ec12300-e2eb-11ea-8907-291e3ab5559e.png)
