### ISSUE TITLE
The web data connector requires user approval to retrieve data

### ISSUE THREAD

**Issue by MinMiguelM** [tableau/webdataconnector#400]
Hi, 

I'm getting next error using my WDC:
_The user has not yet visited the url 'http://localhost/tableau.html' on this machine._

The same WDC works on Tableau 2020.3 but when I try on Tableau 2019.2 I got that error. 

Any ideas?
Thanks in advance.

**Comment by theoutlander** [comment]
Between those two versions, QT was upgraded to use QTWebEngine from QTWebkit. 

I'm curious, are you redirecting to the auth url before that WDC was loaded? It's hard to tell without looking at your code.

**Comment by MinMiguelM** [comment]
No, I am not redirecting, there is only one page that is tableau.html. I made a http request to a rest server that is hosted on http://localhost.

About the version of QT, this connector in its first versions worked on 2019.2 but when QT was upgraded I changed it because on newer versions the connector throws some random errors, now it works on 2020.3 but 2019.2 it does not.

I don't know if the change that I made is related to this error. 
In the first version of the connector I triggered the initialization with this code (https://github.com/tableau/webdataconnector/issues/165):
```
            if (!!window.tableauVersionBootstrap) {
                window._tableau.triggerInitialization();
            }
            if (!window.tableauVersionBootstrap) {
                var DOMContentLoaded_event = window.document.createEvent("Event");
                DOMContentLoaded_event.initEvent("DOMContentLoaded", true, true);
                window.document.dispatchEvent(DOMContentLoaded_event);
            }
```

Then, I updated it removing that code and creating an init function, it looks like this:
```
(function() {
    controller = new Controller();

    var connector = tableau.makeConnector();
    connector.getSchema = controller.getSchema;
    connector.getData = controller.getData;

    tableau.registerConnector(connector);
})();
```

That was the only big change on the connector.

Hope it can help, thanks in advance.

**Comment by theoutlander** [comment]
Thanks for the details @MinMiguelM. I think that specific error message is shown when that URL isn't in the browser history. If you are going to http://localhost and later redirecting to http://localhost/tableau.html, it is likely the reason for that error message as the second URL might not be in the history.

Your new code block is the preferred way of initializing the connector.

**Comment by MinMiguelM** [comment]
It does not solve my problem.
I will continue looking for a solution.

**Comment by theoutlander** [comment]
If you can post your code, I can check if something stands out.
