### ISSUE TITLE
Tableau Desktop. Chromium Debugger Stops Working after WDC submits

### ISSUE THREAD

**Issue by rrecuero** [tableau/webdataconnector#402]
Hi there,

I have developed a WDC in React and everything works great in the Simulator.

However, whenever I run in through the tableau Desktop, it hangs up on `Executing Query` screen after clicking submit on the WDC:

<img width="751" alt="Screen Shot 2020-08-20 at 11 50 28 AM" src="https://user-images.githubusercontent.com/541599/90812782-7b25a000-e2db-11ea-8ce4-361d23fbd155.png">

I can't debug it using Chromium because after calling `submit()` the window closes and shows the following.

![Screen Shot 2020-08-20 at 11 49 48 AM](https://user-images.githubusercontent.com/541599/90812845-9395ba80-e2db-11ea-81b8-51181a377547.png)

Any help as to how to debug this issue will be highly appreciated

**Comment by theoutlander** [comment]
I think that is expected because submit closes the UI. You might want to try to reattach it once it goes to this phase. 

Another thing you can try is call tableau.log(msg) and check your logs in the log file that tableau generates.

**Comment by rrecuero** [comment]
Ok, using log works. Thank you
