### ISSUE TITLE
IS it possible to get data directly to tableau with out submit button in HTML

### ISSUE THREAD

**Issue by PrabhuSelvaraj300** [tableau/webdataconnector#405]
Please consider below example :
Earthquake Example : HTML File
<html>
<head>
    <title>USGS Earthquake Feed</title>
    <meta http-equiv="Cache-Control" content="no-store" />
    
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    
    <script src="https://connectors.tableau.com/libs/tableauwdc-2.3.latest.js" type="text/javascript"></script>
    <script src="../js/earthquakeUSGS.js" type="text/javascript"></script>
</head>
body

    <div class="container container-table">
        <div class="row vertical-center-row">
            <div class="text-center col-md-4 col-md-offset-4">
        <button type = "button" id = "submitButton" class = "btn btn-success" style = "margin: 10px;">Get Earthquake Data!</button>
            </div>
        </div>
    </div>

</html> 

In this i dont want button as " GET Earthquakedata. once i load html page it want to directly fetch data.
 Below is the Js code. for connection

    tableau.registerConnector(myConnector);

    // Create event listeners for when the user submits the form
    $(document).ready(function() {
        $("#submitButton").click(function() {
            tableau.connectionName = "USGS Earthquake Feed"; // This will be the data source name in Tableau
            tableau.submit(); // This sends the connector object to Tableau
        });

Please let me know what i need to change in HTML and JS to fetch data directly with out interface(i.e with out Get earthquakedata in HTML Page button)

Thanks 
Prabhu

**Comment by KeshiaRose** [comment]
Hi @PrabhuSelvaraj300, to [run the connector without user interaction](https://tableau.github.io/webdataconnector/docs/wdc_custom_init_and_shutdown.html) you can delete the $(document).ready() section entirely and then add a custom `init` function before you register the connecter. So the end of your file should look something like this: 
```
myConnector.getData = ...blah blah blah

myConnector.init = function(initCallback) {
  initCallback();
  tableau.connectionName = "USGS Earthquake Feed";
  tableau.submit();
};

tableau.registerConnector(myConnector);
```
-Keshia
