### ISSUE TITLE
Want to Pass a value from file for Parameters

### ISSUE THREAD

**Issue by PrabhuSelvaraj300** [tableau/webdataconnector#406]
how can i pass a list of values as parameter values from file from specified location and get response in tableau webdata connector

i.e passing CSV file with 3 columns as parameter values( CSV file is from specied location)

**Comment by KeshiaRose** [comment]
Hi @PrabhuSelvaraj300, if your WDC has access to the location where the file is hosted you can fetch the data to use in your WDC. Here's one way to do it with jQuery: https://www.js-tutorials.com/jquery-tutorials/reading-csv-file-using-jquery/. Another way would be to use the Fetch API:
```
fetch("./data.csv")
  .then(response => response.text())
  .then(text => {
    //Use CSV text
  });
```

**Comment by PrabhuSelvaraj300** [comment]
So after using Fetch , then we need to pass text object in getjson in our JS code?

**Comment by KeshiaRose** [comment]
It depends, what are you trying to accomplish? Could you give me some more info?

**Comment by PrabhuSelvaraj300** [comment]
Please find below example 

EarthQuake Example:
(function() {
    // Create the connector object
    var myConnector = tableau.makeConnector();

    // Define the schema
    myConnector.getSchema = function(schemaCallback) {
        var cols = [{
            id: "id",
            dataType: tableau.dataTypeEnum.string
        }, {
            id: "mag",
            alias: "magnitude",
            dataType: tableau.dataTypeEnum.float
        }, {
            id: "title",
            alias: "title",
            dataType: tableau.dataTypeEnum.string
        }, {
            id: "location",
            dataType: tableau.dataTypeEnum.geometry
        }];

        var tableSchema = {
            id: "earthquakeFeed",
            alias: "Earthquakes with magnitude greater than 4.5 in the last seven days",
            columns: cols
        };

        schemaCallback([tableSchema]);
    };

    // Download the data
    myConnector.getData = function(table, doneCallback) {
        $.getJSON("https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_week.geojson", function(resp) {
            var feat = resp.features,
                tableData = [];

            // Iterate over the JSON object
            for (var i = 0, len = feat.length; i < len; i++) {
                tableData.push({
                    "id": feat[i].id,
                    "mag": feat[i].properties.mag,
                    "title": feat[i].properties.title,
                    "location": feat[i].geometry
                });
            }

            table.appendRows(tableData);
            doneCallback();
        });
    };

    tableau.registerConnector(myConnector);

    // Create event listeners for when the user submits the form
    $(document).ready(function() {
        $("#submitButton").click(function() {
            tableau.connectionName = "USGS Earthquake Feed"; // This will be the data source name in Tableau
            tableau.submit(); // This sends the connector object to Tableau
        });
    });
})();


in the above example we are retrieving ID, MAG, TITLE and location. For example, i have 6 values for ID in CSV file which i need to pass in above Json.
How can i do.

Thanks & Regards,
Prabhu

**Comment by KeshiaRose** [comment]
Is this a publicly available CSV?

**Comment by KeshiaRose** [comment]
Here's one way to bring in the data in your getData function:
```
myConnector.getData = function (table, doneCallback) {
  let url = "https://server.com/file.csv";
  fetch(url)
    .then((response) => response.text())
    .then((csv) => {
      let tableData = [];
      let data = Papa.parse(csv).data; // Parse csv into an array
      let fields = data.shift(); // Grab first row as field names
      // Assumes columns are always in the same order
      for (let row of data) {
        tableData.push({
          id: row[0],
          mag: row[1],
          title: row[2],
          location: row[3]
        });
      }
      table.appendRows(tableData);
      doneCallback();
    });
};
```
This uses [Papa Parse](https://www.papaparse.com/) to parse out the csv but it's not necessary if your csv is simple.
