### ISSUE TITLE
tableData variable undefined in WDC tutorial

### ISSUE THREAD

**Issue by mkvenkatesh** [tableau/webdataconnector#41]
While following through the new [WDC Tutorial](http://tableau.github.io/webdataconnector/docs/wdc_tutorial#get-data), in the **Get the data** section, it appears `tableData` variable is not initialized which throws an error at the `tableData.push` statement.

**Comment by jdomingu** [comment]
Nice catch! Thanks. Fixed [here](https://github.com/tableau/webdataconnector/commit/2d56974ba380f2ab10329efbb891e82c9f971638).
