### ISSUE TITLE
{{ site.baseurl }} Not evaluated then running simulator, causes style and urls to be broken

### ISSUE THREAD

**Issue by dingobar** [tableau/webdataconnector#412]
See this screenshot:
![image](https://user-images.githubusercontent.com/41419288/96460641-b54fe700-1223-11eb-8dc9-1230361a73f2.png)

**Comment by KeshiaRose** [comment]
Hi @dingobar, to my knowledge the Simulator and the examples are the only things intended for you to be running locally. Everything else is just for the hosted GitHub pages and is built with Jekyll. If you need to run the pages locally you can follow [this guide](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages-and-jekyll).
-Keshia
