### ISSUE TITLE
ES6 support in webkit

### ISSUE THREAD

**Issue by dingobar** [tableau/webdataconnector#413]
Hi,

In the docs, you state
>Note: The browser used inside Tableau is QT WebKit, which does not natively support new ES6 features. If you wish to take advantage of newer features (such as promises) when building WDCs you will need to use a polyfill.

ES6 is now 5 years old, thus not "new". Is support for modern JavaScript on the roadmap?

**Comment by KeshiaRose** [comment]
Hi @dingobar, that note is outdated. In 2019.4 we upgraded to Qt WebEngine which does support ES6 and some newer features. You can double-check if a specific feature you want to use is supported by connecting to https://html5test.com/ in the WDC dialog. Thanks for bringing this up, I'll make sure to get the note fixed!
-Keshia

**Comment by KeshiaRose** [comment]
Updated the note.
