### ISSUE TITLE
Tableau Web Data Connector no working 2020.x.x Tableau Desktop 

### ISSUE THREAD

**Issue by anujkumartech** [tableau/webdataconnector#419]
Hi,

Our connector works on 2019.x.x Desktop Versions but not on 2020.x.x versions.
In 2020.x.x  when user clicks on load data, there is constant spinning circle.
There are no entries in tabprotosrv.txt file for data gather phase, only logs present are in log.txt file

![Tableau_Isssue_data_load](https://user-images.githubusercontent.com/7864705/99454151-02db7480-28f4-11eb-9044-1265d9ea1c5c.png)

**Comment by javakishore** [comment]
have you checked the WDC service logs whether the WDC gather phase is reaching the service?

**Comment by anujkumartech** [comment]
I don't see get data phase called. I see tableau's getSchema and then subsequent schemaCallback done but then there are no logs for tableau's getData.

**Comment by theoutlander** [comment]
Which version of 2019.x did you try? There was a major upgrade in 2019.4 from QTWebKit to QTWebEngine.

Also, which version of WDC lib are you using?
