### ISSUE TITLE
the docs for wdc on server could do with some work

### ISSUE THREAD

**Issue by henryw374** [tableau/webdataconnector#420]
The docs in this project https://github.com/tableau/webdataconnector/blob/master/docs/wdc_use_in_server.md don't contain any detail about whitelisting, whilst the docs they point to (https://help.tableau.com/current/server/en-us/datasource_wdc.htm) contain an example that is a real wdc, but for which the config would be wrong (see https://github.com/dtreskunov/wta-wdc/issues/1).

It's a shame that the community connectors don't each include a minimal whitelist config as far as I can see. 

I also tried using a json entity file, as described in https://help.tableau.com/current/server/en-us/entity_wdc.htm, but the secondary whitelist didn't work  - because `(https://stephdietzel.github.io/*)` should be `(https://stephdietzel.github.io/(.*))` - on windows at least.  And when refreshing we couldn't see any useful log output in the tableau server, the refresh just times out.

The clearest documentation I found for wdc whitelist was contributed by a user in this ticket: https://github.com/tableau/webdataconnector/issues/417#issuecomment-725865246

**Comment by KeshiaRose** [comment]
Agreed, I'll see if we can get them updated soon!
