### ISSUE TITLE
The simulator works normally, OAuth 404 in tableau

### ISSUE THREAD

**Issue by luozewei** [tableau/webdataconnector#421]
My connector has two authentication modes to obtain data. One is OAuth and the other is apikey. Both work normally in the simulator. However, when testing on tableau, the apikey mode works normally. However, if you jump to the authentication authority and submit the password through OAuth, it will 404 when you submit the password, or when Microsoft authentication returns to our certification center, I need to make those adjustments

**Comment by KeshiaRose** [comment]
Hi @luozewei,
Have you tried [debugging in Desktop instead](https://tableau.github.io/webdataconnector/docs/wdc_debugging.html#debug-chrome)? The Simulator does not accurately reflect the browser we use in Desktop and there may be features that aren't available.
-Keshia

**Comment by luozewei** [comment]
debugging in desktop  error:
Navigated to http://localhost:9000/devtools/inspector.html?ws=localhost:9000/devtools/page/00084d24-5a7d-41fc-aa5e-7750c6bbc854
inspector.js:2964 Uncaught TypeError: document.registerElement is not a function
    at Object.UI.registerCustomElement (inspector.js:2964)
    at inspector.js:2976
    at inspector.js:2978

**Comment by luozewei** [comment]
The qtwebengine / 5.1.0 does not support the samesite property of cooike. I can only ask the background to filter out the version of qtwebengine / 5 on the server.
`  if(NotDisallowsSameSiteNone(userAgent))
            {
                options.SameSite = (SameSiteMode)(-1);
            } `
` private static bool NotDisallowsSameSiteNone(string userAgent)
        {
             if (userAgent.Contains("QtWebEngine/5"))
            {
                return true;
            }
            return false;
        }`
I hope you can upgrade to the latest version or support Cooike SameSite as soon as possible

**Comment by luozewei** [comment]
closed issuse @KeshiaRose
