### ISSUE TITLE
WDC not allowing appending data when union with XLSX

### ISSUE THREAD

**Issue by suraj-converse** [tableau/webdataconnector#427]
I know that when we union **2 XLSX** files, it allows us to append the data to those excel files. But I joined an **XLSX file and WDC** . Then it's not allowing me to _append data_ to that XLSX file. 

Is there any different approach that I can try where I have the option of **appending and relation with WDC** ??

![join 2](https://user-images.githubusercontent.com/71890617/103865886-7abf5300-508a-11eb-97d0-d811d62c8779.PNG)

![Screenshot (16)](https://user-images.githubusercontent.com/71890617/103865916-86127e80-508a-11eb-9cf8-7f22e6e9b99a.png)

**Comment by KeshiaRose** [comment]
Unfortunately, this feature is not available for WDCs.

**Comment by suraj-converse** [comment]
Thank you for your reply 👍.  Is there any kind of workaround that I could do @KeshiaRose?

**Comment by KeshiaRose** [comment]
Hmm, it depends on the data you're working with. Do you have control of the WDC? If so can you add the data you need there? Alternatively, you may want to think about using another tool to bring the data in, perhaps the [Hyper API](https://help.tableau.com/current/api/hyper_api/en-us/index.html). What kind of data are you working with, and where is it coming from?

**Comment by suraj-converse** [comment]
Yes, I have complete control over the WDC. In fact, I built it. It's an API that gets the data from our server. Another one is an excel file which I receive daily. I have refresh data in Tableau online daily. 

Do you think hyper API will work for this?

**Comment by KeshiaRose** [comment]
Wonderful! Yes, I think you should try building a data source with the Hyper API, you'll be able to bring in data from multiple different sources into one extract. Take a look at the [documentation](https://help.tableau.com/current/api/hyper_api/en-us/index.html) and these [samples](https://github.com/tableau/hyper-api-samples) to get started!

You could also try and stick with the WDC route and try to find a way to bring the Excel file in there, perhaps uploading it to something like Google Sheets first? Those are the two directions I would try out!
