### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by visualisedata** [tableau/webdataconnector#428]
In https://tableau.github.io/webdataconnector/docs/wdc_cors.html there is a section titled Make requests through a proxy server

At the bottom of this section, the text says:

If you want to share your connectors with other users in your organization, you can download and configure a production proxy server, or you can use a free, public proxy server like http://cors.io/. or https://crossorigin.me/.

But neither of these domains are operational.  

Can you please remove and supply new (operational) resources ?

**Comment by d45** [comment]
Thank you for pointing this out. 
We've replaced proxy server example with this one: 
https://cors-anywhere.herokuapp.com/

**Comment by theoutlander** [comment]
Thanks, @d45 for fixing this issue.
