### ISSUE TITLE
WDC getting errors while passing jwtey to a form and connecting to API

### ISSUE THREAD

**Issue by nischit07** [tableau/webdataconnector#433]
Hi,

I'm new to Tableau and I'm trying to connect Tableau to our API which requires jwt. I want to pass jwt to a form in HTML which will then allow to connect to the API. Do we have templates that supports this mechanism?

**Comment by KeshiaRose** [comment]
You can store the JWT in tableau.password when you submit the connector. Here is one of my WDCs where I store the API Key in tableau.password to be used later: https://glitch.com/edit/#!/simple-airtable-wdc
