### ISSUE TITLE
Ayuda con el WDC - Tableau

### ISSUE THREAD

**Issue by MiguelGB2021** [tableau/webdataconnector#434]
Buenas Tardes

Estoy creando un WDC para conectar unos datos de un API. 
Los datos del API Están en Formato JSON.

La maquina donde estoy trabajando tiene SO Windows 10

Leí la documentación para construir el WDC desde el siguiente link : https://tableau.github.io/webdataconnector/docs/index.html

Según la guía descargue git y node, luego clone la carpeta del Web data connector.

![Repositorio](https://user-images.githubusercontent.com/77864854/105562036-b2fb9e00-5ce6-11eb-9257-ebde6b5eda41.PNG)

Abró una linea de comandos, primero ubico la carpeta clonada y luego ejecuto el siguiente comando  
"npm install --production" al terminar aparecen varios errores.

Investigue en internet y el comando que se debe ejecutar es el siguiente "npm install" pero tambien aparecen varios errores una vez finaliza la ejecución.

![Captura npm install](https://user-images.githubusercontent.com/77864854/105562337-c824fc80-5ce7-11eb-9520-1b1d87ca82c8.PNG)

Ignoro los mensajes y procedo a ejecutar el comando "npm start"
se empeoran las cosas

![Captura npm start](https://user-images.githubusercontent.com/77864854/105562408-07534d80-5ce8-11eb-8db7-3446238372fd.PNG)

Solicito su ayuda para que me indiquen que estoy haciendo mal. O si hace falta algo en la configuración Inicial.

**Comment by KeshiaRose** [comment]
Hi @MiguelGB2021, the documentation and package are pretty old so I would not use them for your WDC development. Try this instead: 
1. Create a new working folder and place your WDC files there.
2. Open the command prompt and run `npm install --global http-server`. This will globally install the same [development server](https://www.npmjs.com/package/http-server) we used.
3. Once installed, navigate to your working folder in the command prompt and then run `http-server`. This has now started a local dev server that is serving your WDC files.
4. Open your browser to [http://localhost:8080](http://localhost:8080) and you should see your WDC.

Let me know if this works for you!

**Comment by MiguelGB2021** [comment]
Hola Keshia

Antes que nada quiero agradecerte por ayudarme con este inconveniente.

Lastimosamente realice el procedimiento que me sugeriste y aún tengo errores.

![image](https://user-images.githubusercontent.com/77864854/105869030-cea3c480-5fc4-11eb-973a-7b2fcc1cfcde.png)

**Comment by KeshiaRose** [comment]
There is a period at the end of 'http-server.', remove it. It should be: `npm install --global http-server`

**Comment by MiguelGB2021** [comment]
Muchas Gracias.... Ya pude acceder
