### ISSUE TITLE
Unable to add to community_connectors.json 

### ISSUE THREAD

**Issue by EMahendren** [tableau/webdataconnector#437]
I am unable to add to community_connectors.json - the error message is "Travis-CI build could not complete due to an error"

![error_msg](https://user-images.githubusercontent.com/59929398/106175858-81734e80-618e-11eb-8289-0ec54b363ca2.png)

**Comment by leozusa** [comment]
Same here, it seems like TravisCI has been broken since November 2020! Please fix!!!
![TravisErrors](https://user-images.githubusercontent.com/3324234/119741590-e0925880-be3a-11eb-9f89-33cd6b332f1d.png)

**Comment by paulsuh** [comment]
Bumping this issue -- all connectors are failing the CI test due to this bug.

**Comment by theoutlander** [comment]
Thanks for reporting this. We will look into it this week.

**Comment by maxrandolph** [comment]
Hello, the travis pipeline should be passing now. I'll close this issue as it relates to the pipeline itself. If you run into additional issues, please open a new issue.
