### ISSUE TITLE
Tableau Data source with stale user credentials using our WDC was doing 300k plus calls to auth server and caused issues. if a tableau WDC refresh call fails because of stale user credentials

### ISSUE THREAD

**Issue by tlkchew** [tableau/webdataconnector#438]
Tableau Data source connector with incorrect user credentials using our WDC was doing 300k plus calls to auth server and caused issues. this is causing major issues with the authentication server.  
WDC  should stop the calls  after 3 or 6 incorrect authentication.

**Comment by KeshiaRose** [comment]
Hi @tlkchew, do you have any more details from the user of the connector? Such as how the connector was being refreshed? Tableau Server does not auto-retry refreshes when the connection fails. And if the refresh is on a schedule, after 5 failed attempts it stops refreshing.
-Keshia
