### ISSUE TITLE
Error on Influxdb web data connector

### ISSUE THREAD

**Issue by Faouzizi** [tableau/webdataconnector#439]
Since February 5, the influxdb web data connector no longer work. Did you have more information about this issue ? 
I use Tableau desktop 2019.2 and the error is "SyntaxError: Invalid character: '`' file: https://tagyoureit.github.io/InfluxDB_WDC/InfluxDB_WDC.js line: 68" 
Regards

**Comment by KeshiaRose** [comment]
You will need to bring this issue to the developer of the WDC: https://github.com/tagyoureit/InfluxDB_WDC/issues/new/choose
