### ISSUE TITLE
the docs for incremental refresh seem inconsistent

### ISSUE THREAD

**Issue by henryw374** [tableau/webdataconnector#440]
On the docs page https://tableau.github.io/webdataconnector/docs/wdc_incremental_refresh.html 

it says 
```
WDC API supports three data types for the incremental refresh column: DateTime, Date, and integer
```

but the column using in the example is of type "string". in getData this is parsed into an int. Surely this wouldn't work - ie col is the wrong type?

**Comment by KeshiaRose** [comment]
Good catch! I've updated it to match the actual data types for the sample including the correct type for the incremental ID.
