### ISSUE TITLE
Is the tableau browser safe?

### ISSUE THREAD

**Issue by dingobar** [tableau/webdataconnector#441]
Does it use SSL/TLS? Are session data such as cookies encrypted? When I add data to `tableau.connectorData`, is it then stored server-side?

**Comment by maxrandolph** [comment]
The Tableau browser would use SSL/TLS as long as you're connecting to your WDC over `https://`. Cookies are stored in memory of the Tableau process. Cookies are encrypted to the same standards found in web browsers like Chrome. Data added to `tableau.connectionData` will be stored server side when you publish the data source. If you need to include sensitive details such as a password or access token, you should use `tableau.password`. This value is encrypted server side when a data source with "embedded credentials enabled" is published to server.

By the way for future reference. you may have an get a quicker response asking these questions here: https://community.tableau.com/s/explore-forums
