### ISSUE TITLE
HTTP basic auth doesn't work with tableau desktop

### ISSUE THREAD

**Issue by NimChimpsky** [tableau/webdataconnector#445]
Using https://tableau.github.io/webdataconnector/Simulator/ works as expected and a popup for username and password appears.

However tableau desktop gives error.

**Comment by KeshiaRose** [comment]
HI @NimChimpsky, Have you tried debugging in Desktop? Since the simulator runs in your in browser it doesn't behave the same way as the browser in Desktop: https://tableau.github.io/webdataconnector/docs/wdc_debugging.html#debug-chrome
-Keshia

**Comment by NimChimpsky** [comment]
hi fyi I am not debugging the implementation of paid software, that is shown to work using yr own simulator.

**Comment by theoutlander** [comment]
@NimChimpsky we are not asking you to debug Tableau, rather your WDC connector in Tableau. 

Without seeing your code, the error details, or screenshots of the error, debugging your connector in Tableau is the best way to find the root cause.

**Comment by NimChimpsky** [comment]
basic http auth doesn't work with tableu desktop.  My code just uses yr examples that work with the simulator.
