### ISSUE TITLE
`sudo npm install --production` fails

### ISSUE THREAD

**Issue by benjcabalona1029** [tableau/webdataconnector#448]
I am following the steps outlined https://tableau.github.io/webdataconnector/docs/. 

Node version = v14.16.1
npm version = 7.11.1

I have tried running

`sudo npm install` and it returns the same error.

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: webdataconnector@2.0.0
npm ERR! Found: eslint@4.19.1
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^4.18.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^2.9.0" from eslint-config-airbnb@9.0.1
npm ERR! node_modules/eslint-config-airbnb
npm ERR!   dev eslint-config-airbnb@"^9.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/myusername/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myusername/.npm/_logs/2021-04-26T06_17_44_515Z-debug.log
```

**Comment by benjcabalona1029** [comment]
Fixed it by running

`sudo npm install --global http-server`

then instead of `npm start` i am running `http-server`.

I recommend the documentation be updated, since this is usually the first step people will be doing while developing a wdc.

**Comment by chenteng2016** [comment]
Nick and I migrated the deprecated corsproxy, would you please pull the latest master to see if npm start works with cors proxy for your scenario? thanks!

**Comment by NathanGloyn** [comment]
I have just cloned the repo and tried to follow the instructions in the getting started document and run into the same error.

I'm on windows and have tried running it both normal and elevated priviledges but get the same result.

I can also confirm that if I install http-server and run that it starts (haven't gotten further than this at this point).

I've attached the npm log [2021-06-17T13_15_50_267Z-debug.log](https://github.com/tableau/webdataconnector/files/6670503/2021-06-17T13_15_50_267Z-debug.log)

**Comment by chenteng2016** [comment]
@NathanGloyn @benjcabalona1029 thanks for the information! We suggested pulling the latest master to "npm start" with the migrated cors proxy because I thought "npm install --production" was successful with sudo.

For the dependency tree resolution issue, looks like npm will alert even for dev dependencies for "npm install --production". 

Could you please try "npm install --production --legacy-peer-deps"? (also try running as admin on windows or with sudo on mac if there is any permission issue).

@NathanGloyn if it still does not work please offer your detailed node and npm version, and we could follow up further. Thanks.

**Comment by NathanGloyn** [comment]
Hi @chenteng2016 ,

I ran `npm install --production --legacy-peer-deps` and it worked straight off didn't need elevated privileges and then running `npm start` worked as you would expect.

Let me know if you want me to try anything else out

**Comment by chenteng2016** [comment]
.npmrc also involves --legacy-peer-deps, corsproxy migrated for npm start; please help re-open or let us know if there is still issue related, thanks for contributing to webdataconnector!
