### ISSUE TITLE
WDC can't create an extract

### ISSUE THREAD

**Issue by HoangHa91** [tableau/webdataconnector#449]
Hi
I have problem with my WDC.
Previously, my WDC have 31 columns in schema and it working fine, but when I update  one new column and change incrementColumnId to this column, my WDC can't create an extract in Desktop version anymore, but it still can pull complete data and in Public version, everything is still fine. 
I'm using WDC 2.1.0 with tableau 2021.1

**Comment by KeshiaRose** [comment]
HI @HoangHa91, can you share your code? What data type was the new column? Only integers, dates, or date-times are accepted.
-Keshia
