### ISSUE TITLE
Please merge #457, it's meant to allow linking connectors directly in the community via fragment in URL

### ISSUE THREAD

**Issue by leozusa** [tableau/webdataconnector#458]
https://github.com/tableau/webdataconnector/pull/457 This change is meant for us community members to be able to link our connectors on the portal with a fragment in the URL. It's been tested on all major browsers, with a nice jquery animation to drive user's attention. I've set up https://leozusa.github.io/webdataconnector/community/#twitter or https://leozusa.github.io/webdataconnector/community/#wanikani_connector, (or any other) as examples to see it in action, I'll drop the pages once merged.

**Comment by theoutlander** [comment]
@maxrandolph please validate/merge this fix after travis is passing

**Comment by maxrandolph** [comment]
This has been merged. Thank you for your contribution @leozusa!
