### ISSUE TITLE
Doing requests before calling the SDK

### ISSUE THREAD

**Issue by idris-maps** [tableau/webdataconnector#460]
Is it at all possible to make any requests before calling the SDK?

What I want to do: let the user choose what data she wants to use before passing the columns and data to the connector.

I have tried a couple of things in the simulator:

1. Add the SDK script to the HTML file and call it when I know what data needs to be downloaded.

Errors before the connector is registered:

![tableau_befor_init](https://user-images.githubusercontent.com/12154856/121170977-3234dd00-c856-11eb-9d6b-8d0594477fd3.PNG)

Errors when I try to register:

![tableau_after_init](https://user-images.githubusercontent.com/12154856/121171029-437de980-c856-11eb-896b-c4bb7b22ff5e.PNG)

2. Add the SDK script dynamically

![tableau_dynamic_loading](https://user-images.githubusercontent.com/12154856/121171082-542e5f80-c856-11eb-9bb5-3ca15610b76a.PNG)

3. Same as 2, but using a [hack from 2017](https://github.com/tableau/webdataconnector/issues/165#issuecomment-294270108), simulating a `DOMContentLoaded` event when the SDK has loaded.

![tableau_2017_hack](https://user-images.githubusercontent.com/12154856/121171315-a2dbf980-c856-11eb-87d7-4fd5e4f33c5c.PNG)

Am I doing something wrong or is this simply not possible?

`tableau.init()` does not exist.

**Comment by leozusa** [comment]
I like a lot the concept. I suggest using the chrome debug method (https://tableau.github.io/webdataconnector/docs/wdc_debugging.html#debug-chrome) and glitch for debugging the server-side, also please check https://github.com/leozusa/visier-tableau-basic-auth/blob/main/public/script.js where I create a couple of empty objects (tableau and Papa) so the IDE stopped complaining because they didn't exist. Anyways, the tableau object does exist when running inside Tableau, and you'll be able to test your strategy.

**Comment by KeshiaRose** [comment]
Hi @idris-maps, can you share your code? I'm not sure why you would want to delay loading the wdc lib when you don't need to submit the WDC until tableau.submit() is called. You have all the time you want to collect information from the user, and make any additional calls before kicking off your getSchema function.  Here is a really basic sample of a WDC where the user inputs the city they want to get weather data from and then it does a fetch to show a preview of the city on a map for confirmation. There is no need to delay loading the library: https://glitch.com/edit/#!/datadev-weather-wdc
-Keshia

**Comment by KeshiaRose** [comment]
BTW @leozusa if you're going to copy/modify my WDC code it would be really nice if you mentioned my name and that you started with my code 😉

**Comment by leozusa** [comment]
My bad! Was considering to use it just for starters but in the end proved too useful! I'll add it in my next release!

**Comment by idris-maps** [comment]
Hello @KeshiaRose . Thank you for the example code. 

As far as I can see you define  `getSchema` and `getData` on pageload. In my use case I do not know which columns the dataset will have, nor how the data will be fetched until the users make some choices. 

I guess I did not express myself correctly, what I want is to be able to define these two functions after the user has maid some choices.

**Comment by KeshiaRose** [comment]
Hi @idris-maps, Nope I think I should have just shown you a better sample 😄 . You still do not need to delay the loading of the library. Here is a generic CSV connector where the schema is defined after getting the CSV on the fly: https://github.com/KeshiaRose/Basic-CSV-WDC/blob/master/public/script.js And here is one for JSON/XML where you can actually select the fields you want to bring in or create separate tables: https://github.com/KeshiaRose/JSON-XML-WDC/blob/master/public/script.js

In both cases, I have no clue what the schema or data looks like and I still am not delaying the load of the API. Again you can fully control what happens in the getSchema and getData functions so you are able to wait until you get input from the users, store that data in tableau.connectionData, and then do whatever you need to do later.

**Comment by idris-maps** [comment]
Thank you @KeshiaRose, for the quick answer and the examples.

If I understand correctly, the `getSchema` and `getData` functions need to be defined upfront but they are not called until `tableau.submit()` is called. And whatever data that they need is passed with `tableau.connectionData`, stringified when set and parsed when retrieved in the above mentioned functions.

Will try it out

**Comment by idris-maps** [comment]
Works fine. Thank you for your help @KeshiaRose
