### ISSUE TITLE
Auto refresh data in Tableau Public

### ISSUE THREAD

**Issue by samanthahw21** [tableau/webdataconnector#468]
hi, i have used a tableau webconenctor here to fetch csv data from github and i build tableau viz by extracting data via the connector directly from the github datasource ( using the URL raw data form)  

But the Viz display dashboard will not get refresh when there is a new data coming in to the github data source. 

Any idea what are the steps i need to do in order the dashboard get refresh ?

I am not familiar with googlesheet. Maybe your suggestion is much apprecaited.

thanks
Sam

**Comment by KeshiaRose** [comment]
Hi @samanthahw21, the only way to automatically update a WDC data source is to refresh them on Tableau Server or Tableau Online. When using Tableau Desktop you will need to manually hit "refresh" and Tableau Public does not support automatic refreshes for WDC. If you want your data to update automatically in Tableau Public you will need to use Google Sheets as your data source. You could possibly use the GitHub and Google Sheet APIs to periodically copy the data into a Google Sheet instead and that could be updated on Tableau Public every 24 hours.
-Keshia
