### ISSUE TITLE
REST Data Connector not updating data

### ISSUE THREAD

**Issue by sepodele** [tableau/webdataconnector#471]
It seems like the 'REST Data Connector' in the Community Portal doesn't update data when extract is refreshed in Tableau Desktop (anymore?). Can anyone confirm?

I've tried for instance with a simple GET request on https://qrng.anu.edu.au/API/jsonI.php?length=1&type=uint8 that simply returns a random number.

I've created an issue to the developer but he doesn't seem to respond. I was hoping someone here would be able to see what's wrong in the code that prevents it from updating.

Source: https://github.com/niranjan94/rest-data-connector
WDC: https://rdc.codezero.xyz/#/

**Comment by KeshiaRose** [comment]
Hi @sepodele, unfortunately, we won't be able to help with this code and you'll need to wait for the developer to respond. But what data you are trying to connect to?

**Comment by sepodele** [comment]
@KeshiaRose The intention was https://api.nsd.no/dbhapiklient/ .

**Comment by KeshiaRose** [comment]
Looks like there is a CSV output option perhaps this could work for you?  https://basic-csv-wdc.herokuapp.com/

**Comment by sepodele** [comment]
Thanks but the CSV output option is only for certain tables in that API.
