### ISSUE TITLE
Facebook Web Connector not working

### ISSUE THREAD

**Issue by shaheensr787** [tableau/webdataconnector#472]
https://tableaujunkie.com/post/123558558693/facebook-web-data-connector

Please suggest why is this not working, screenshot attached.
Or suggest a better web connector please.[
![Screen Shot 2021-09-15 at 12 19 05 PM](https://user-images.githubusercontent.com/90758403/133402209-1139b937-2bd6-4938-b73f-5b09c2c2ad32.png)

**Comment by KeshiaRose** [comment]
Hi @shaheensr787 unfortunately I am not aware of another Facebook WDC but you will need to [reach out to Alex Ross](https://github.com/alexfrancisross/FacebookWebDataConnector/issues) who created that WDC with this issue.

**Comment by alexfrancisross** [comment]
@shaheensr787 unfortnately my Facbook App has now been deactivated so this WDC no longer works. In addition it would need to be updated to use the WDC 2.0 framework which I have not had the opportunity to implement.
