### ISSUE TITLE
how to update and existing wdc connectiondata string?

### ISSUE THREAD

**Issue by duronrulez** [tableau/webdataconnector#479]
So we had an up and running WDC service, all good. But recently we've updated the service to include dynamic table definitions, which works great for new data sources from that service.

The problem is the old data sources are now broken because their connectiondata strings are outdated. Is there a way to update the connectiondata for an existing data source? I cannot simply recreate them, because they are incremental extracts that i cannot just delete/create when i want.

I'm fine if i have to edit files on the tableau server as well, just need to get this done. The seeming inflexibility of the configuration once you publish a data source is quite staggering.

**Comment by duronrulez** [comment]
Any thoughts, ideas, feedback?

**Comment by theoutlander** [comment]
It appears that this is not possible. There may be a hacky way to update the .tds files on the server, but I'm not sure what that would look like. This isn't a WDC specific problem either so you might have better luck if you ask this on the broader Tableau Forums.

**Comment by maxrandolph** [comment]
Hi @duronrulez, unfortunately there isn't a great way to do this easily. 

It could potentially be possible to manually update the .tds XML file on server, but that would be a bit hacky and isn't specific to webdataconnector. Would recommend asking on the broader Tableau forums for more info around that route: https://community.tableau.com/s/
