### ISSUE TITLE
Earthquake multi table sample fails in Tableau

### ISSUE THREAD

**Issue by lbrendanl** [tableau/webdataconnector#51]
The earthquake multitable sample fails in Tableau.  This is because the ids it uses for it's column does not match the accepted format for ids in Tableau (I believe having underscores was the offender here).

As a side note: Date pickers in the QT WebKit do not function (at least on Mac).  You can still manually enter a date though.

**Comment by jdomingu** [comment]
Fixed. Updated the sample while I was at it to show a proper join in Tableau.
