### ISSUE TITLE
Simulator doesn't ignore 'tableau.submit' in gatherData phase

### ISSUE THREAD

**Issue by lbrendanl** [tableau/webdataconnector#59]
In Tableau, this is a valid code snippet:

    myConnector.init = function(initCallback) {
      initCallback();
      tableau.submit();
    }

This auto submits a connector so no interactive phase is required.  In the data gathering phase, this submit call is ignored.  However in the simulator this causes the simulator to get into an infinite loop.

**Comment by jagreene** [comment]
Fixed with #88
