### ISSUE TITLE
Caching issues in the simulator

### ISSUE THREAD

**Issue by jdomingu** [tableau/webdataconnector#81]
Here are some things we can try:

* Add more meta tags to disable caching [stackoverflow](http://stackoverflow.com/questions/1341089/using-meta-tags-to-turn-off-caching-in-all-browsers)
* Add -c-1 to the http-server command in package.json [http-server docs](https://www.npmjs.com/package/http-server)
* Worst case: add docs for using Chrome to empty the cache and hard reload. Maybe add docs anyway to identify when you have a caching issue.

**Comment by jdomingu** [comment]
I started with bullet point two (changing the test server command to "http-server -p 8888 -c-1"). I *think* that fixes the problem.

Brendan could you confirm?

**Comment by lbrendanl** [comment]
Fantastic! That appears to have worked.  Closing issue.

**Comment by benlower** [comment]
Word. nice 👍
