### ISSUE TITLE
Doc the simulator src query parameter

### ISSUE THREAD

**Issue by jdomingu** [tableau/webdataconnector#82]
If you enter a URL (into chrome, not simulator), such as this: http://localhost:8888/Simulator/?src=../Examples/JSONMultiTableConnector.html

Then the JSONMultiTableConnector will always be by default loaded into the simulator URL bar when you refresh.  You don’t have to retype the example name.

**Comment by jdomingu** [comment]
Added on the new [debugging page](http://tableau.github.io/webdataconnector/docs/wdc_debugging).

**Comment by iamEAP** [comment]
This looks to have been lost...
