### ISSUE TITLE
Add full page for debugging WDCs

### ISSUE THREAD

**Issue by jdomingu** [tableau/webdataconnector#83]
Add debugging tips, including info about:

* The not supported debugger
* Where to add breakpoints--both in the simulator page and the popup depending on the phase
* Using `?src=` to maintain the same connector in the simulator

**Comment by lbrendanl** [comment]
Should we add default log locations as well? Not as crucial with the unsupported debugger, but still would be useful in some scenarios.

**Comment by jdomingu** [comment]
Added a [wdc_debugging topic](http://tableau.github.io/webdataconnector/docs/wdc_debugging). 

I made a new issue to discuss whether we want to document the log file locations.
