### ISSUE TITLE
Update doc links to point to master when dev merges into master

### ISSUE THREAD

**Issue by lbrendanl** [tableau/webdataconnector#92]
As the docs are in beta until the upcoming release of Tableau 10, the links in the docs will point to the dev branch of the webdataconnector repo.

When we merge dev into master with the release of Tableau 10, we will need to update these links.  This is a place holder for that.  Only location I am currently aware of this is the Samples section in the docs. But we should do a grep for more locations.

**Comment by jdomingu** [comment]
Removed references to the beta and the dev branch, updated the main download link, the samples link, etc.
