### ISSUE TITLE
web dataconnector--xmlconnector 

### ISSUE THREAD

**Issue by yanjing2** [tableau/webdataconnector#97]
i found it  seems can not parse a xml document with xmlconnector, there are some data will be lost,for example,the data---_SENTIMENT (MIXED,NEGATIVE,NEUTRAL,POSITIVE) in the document as bellow is missing,i  don't know how to modify the code, what should i do,kindly please give some advice.thanks very much.

[xml_data.txt](https://github.com/tableau/webdataconnector/files/385621/xml_data.txt)

**Comment by lbrendanl** [comment]
I am closing this issue since the xml connector is not a supported sample connector (though still available through our old releases here on GitHub).
